// node tools/build.mjs  ->  index.html  (then: node tools/make-pdf.cjs)
import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const D=new Function(fs.readFileSync(R+'/tools/data.js','utf8').replace("'use strict';",'')+';return {ACCOUNTS,TRADE_DATA,KHOOD_TRADES,NGX_TRADES,KHOOD_WITHDRAWALS}')();
const VER='1.0.2',ASOF='24 Sep 2026',NAME='Foabao',DATE='September 2026',PDF='Foabao-Financial-Market-Participation-2020-2026.pdf';
const sum=a=>a.reduce((s,x)=>s+x,0),f=(n,d=0)=>n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const usd=(n,d=0)=>(n<0?'−':'')+'$'+f(Math.abs(n),d),sg=(n,d=0)=>`<span class="${n<0?'neg':'pos'}">${n<0?'−':'+'}$${f(Math.abs(n),d)}</span>`,ngn=n=>(n<0?'−':'')+'₦'+f(Math.abs(n)),pc=n=>f(n*100)+'%';
// ₦/$ anchors: user-recorded rates (2024), CBN NFEM levels otherwise; linear between anchors
const FX=[['2024-05-29',1393],['2024-07-05',1530],['2025-02-27',1530],['2025-07-15',1530],['2025-08-28',1510],['2025-10-24',1455],['2026-01-09',1445],['2026-03-25',1380],['2026-05-15',1362],['2026-09-18',1364]];
const rate=d=>{const t=+new Date(d);for(let i=1;i<FX.length;i++){const a=+new Date(FX[i-1][0]),b=+new Date(FX[i][0]);if(t<=b)return t<=a?FX[i-1][1]:FX[i-1][1]+(FX[i][1]-FX[i-1][1])*(t-a)/(b-a)}return FX.at(-1)[1]};
const cls=i=>{i=(i||'').split(',')[0].trim().toUpperCase();if(/^(M?NQ|M?ES|M?YM)[FGHJKMNQUVXZ]\d$/.test(i))return'Futures';if(/WTI|XTI|CRUDE/.test(i))return'Commodities';if(/^(XA|A)[UG][A-Z]{3}$/.test(i))return'Metals';if(/BTC|ETH/.test(i))return'Crypto';if(/^(SPX|SP500|NAS100)/.test(i))return'Equities';if(/^[A-Z]{6}$/.test(i))return'FX';return null};
// ── data
const A=D.ACCOUNTS.filter(a=>a.id!=='NGX'),prop=A.filter(a=>a.type.startsWith('prop')),pers=A.filter(a=>a.type==='personal'),kh=A.find(a=>a.id==='1KHOOD');
const ngx=D.NGX_TRADES.filter(t=>!t.open).map(t=>({...t,net:t.netPnl-t.fees,usd:(t.netPnl-t.fees)/rate(t.closeDate)}));
const ngxG=sum(ngx.map(t=>t.netPnl)),ngxF=sum(ngx.map(t=>t.fees)),ngxN=ngxG-ngxF,ngxU=sum(ngx.map(t=>t.usd));
const fees=sum(prop.map(a=>a.costOfFund)),persPnl=sum(pers.map(a=>a.pnl)),evPnl=sum(prop.map(a=>a.pnl)),passed=prop.filter(a=>a.pnl>0).length;
const overall=persPnl-fees+kh.pnl+ngxU;
const rows=[['Futures','US'],['Equity index CFDs','US'],['US stocks','US'],['Nigerian stocks','NGX'],['FX','Global'],['Commodities','Global'],['Metals','Global'],['Crypto','Global']].map(([k,rg])=>({k,rg,n:0,acc:0,fund:0}));
const row=k=>rows.find(x=>x.k===k),mp={Futures:'Futures',Equities:'Equity index CFDs',FX:'FX',Commodities:'Commodities',Metals:'Metals',Crypto:'Crypto'};
for(const a of A){if(a.id==='1KHOOD')continue;const def=a.id.startsWith('MFFU')?'Futures':'FX';let s=0;for(const t of D.TRADE_DATA[a.id]||[]){const p=t.netPnl||0,sm=/SUMMARY|REMAIN/i.test(t.instrument||''),x=row(mp[(!sm&&cls(t.instrument))||def]);if(!sm)x.n++;x.acc+=p;s+=p}row(mp[def]).acc+=a.pnl-s}
row('US stocks').n=D.KHOOD_TRADES.length;row('US stocks').fund=kh.pnl;row('Nigerian stocks').n=ngx.length;row('Nigerian stocks').fund=ngxU;
const nTr=sum(rows.map(r=>r.n));
const yrs=[2020,2023,2024,2025,2026],Y=Object.fromEntries(yrs.map(y=>[y,{p:0,fee:0,kh:0,ng:0,ev:0}]));
for(const a of pers)Y[a.endDate.slice(0,4)].p+=a.pnl;for(const a of prop){Y[a.startDate.slice(0,4)].fee+=a.costOfFund;Y[a.endDate.slice(0,4)].ev+=a.pnl}
for(const t of D.KHOOD_TRADES)Y[t.closeDate.slice(0,4)].kh+=t.netPnl;for(const t of ngx)Y[t.closeDate.slice(0,4)].ng+=t.usd;
const net=y=>Y[y].p-Y[y].fee+Y[y].kh+Y[y].ng;
const capSz=sum(prop.map(a=>a.size)),pcs=x=>(x<0?'−':'+')+f(Math.abs(x)*100,1)+'%',coh=t=>{const q=prop.filter(a=>t(a.startDate));return{n:q.length,sz:sum(q.map(a=>a.size)),pl:sum(q.map(a=>a.pnl)),up:q.filter(a=>a.pnl>0).length}},c24=coh(d=>d<'2025'),c26=coh(d=>d>'2025'),cum=[];{let c=0;for(const y of yrs){c+=net(y);cum.push(c)}}
// funding: [destination, region, path, {source:USD}]  (unstated sources default to IF)
const F=[['Alpari 2020','Global','Retail',{IF:131.58,PO:163.13}],['Alpari 2023','Global','Retail',{IF:75.35,MO:195.64,TA:156.27}],['MyFundedFX evaluations (4)','Global','Prop',{TA:84,IF:64.22}],['MyFundedFutures evaluations (5)','US','Prop',{MO:165,BA:295,IF:274.5}],['FundedNext and The5ers evaluations (6)','Global','Prop',{IF:133.71}],['1kHooD fund','US','Managed',{TA:1000}],['NGX brokerage','NGX','Retail',{BA:107.64}]];
const SRC=['IF','PO','TA','MO','BA'],GRP={IF:'Personal',PO:'Friend',TA:'Friend',MO:'Family',BA:'Family'},SC={IF:'#051C2C',TA:'#2251FF',PO:'#00A9F4',MO:'#12805C',BA:'#7CC8A9'};
const fs_=Object.fromEntries(SRC.map(s=>[s,sum(F.map(r=>r[3][s]||0))])),cap=sum(Object.values(fs_)),grp=g=>sum(SRC.filter(s=>GRP[s]===g).map(s=>fs_[s]));
const reg=g=>sum(F.filter(r=>r[1]===g).map(r=>sum(Object.values(r[3]))));
const wd=D.KHOOD_WITHDRAWALS,wU=sum(wd.map(w=>w.amountUSD)),gpG=sum(wd.map(w=>w.gpGBP)),lpG=sum(wd.map(w=>w.lpGBP)),lpU=wU*lpG/(gpG+lpG),gpU=wU-lpU,implied=1000+kh.pnl-wU;
const avg=y=>{const s=prop.filter(a=>a.startDate.startsWith(y)&&a.trades>0);return Math.round(sum(s.map(a=>a.trades))/s.length)};
// ── charts
const svg=(w,h,b)=>`<svg viewBox="0 0 ${w} ${h}" role="img">${b}</svg>`;
const dbar=(rs,{w=690,lw=185,fmt=usd,rh=22}={})=>{const pad=66,v=rs.map(r=>r.v),mn=Math.min(0,...v),mx=Math.max(0,...v),sc=(w-lw-pad*2)/((mx-mn)||1),z=lw+pad-mn*sc;
 return svg(w,rs.length*rh+6,`<line x1="${z}" x2="${z}" y1="0" y2="${rs.length*rh+3}" stroke="#8A97A5"/>`+rs.map((r,i)=>{const y=i*rh+3,bw=Math.abs(r.v)*sc,x=r.v<0?z-bw:z;return`<text x="0" y="${y+13}" class="l">${r.l}</text><rect x="${x}" y="${y+2}" width="${Math.max(bw,1)}" height="${rh-9}" fill="${r.c||(r.v<0?'#B3261E':'#2251FF')}"/><text x="${r.v<0?x-4:x+bw+4}" y="${y+13}" text-anchor="${r.v<0?'end':'start'}" class="v">${fmt(r.v)}</text>`}).join(''))};
const stack=(ps,w=690)=>{let x=0;const t=sum(ps.map(p=>p.v));return svg(w,62,ps.map(p=>{const bw=p.v/t*w,o=`<rect x="${x}" y="0" width="${bw-1}" height="28" fill="${p.c}"/><text x="${x+5}" y="18" class="v w">${p.l}</text><text x="${x+2}" y="42" class="l">${pc(p.v/t)}</text><text x="${x+2}" y="54" class="l m">${usd(p.v)}</text>`;x+=bw;return o}).join(''))};
const EV=[['2020-03-11','2020-06-01','COVID-19 pandemic and market crash','Record volatility; first live account (Alpari 2020) traded through it'],['2020-11-03',0,'US presidential election','Rotation and volatility in US equities and the dollar'],['2022-02-24',0,'Russia–Ukraine war begins','Energy and grain shock; commodity and inflation repricing (no participation, 2021–22)'],['2022-11-30',0,'ChatGPT released','Start of the AI investment cycle behind later US equity leadership'],['2023-03-10',0,'Silicon Valley Bank collapse','Regional-bank stress; rates repriced'],['2023-05-29','2023-06-14','Nigeria: subsidy removal and FX unification','Naira devalued; reshaped the cost of dollar capital'],['2023-10-07',0,'Israel–Hamas war begins','Oil and gold volatility; Alpari 2023 traded WTI and gold'],['2024-01-01','2024-02-29','Naira sell-off','Peak dollar cost for Nigerian funders during the 2024 evaluations'],['2024-08-05',0,'Yen carry-trade unwind','Sharp cross-asset drawdown in the middle of the futures evaluations'],['2024-09-18',0,'Fed begins cutting rates','Start of the easing cycle'],['2024-11-05',0,'US presidential election','Trend day for US indices and the dollar'],['2025-04-02',0,'US “Liberation Day” tariffs','Global equity sell-off and rebound; 1kHooD first year'],['2025-06-13','2025-06-24','Israel–Iran 12-day war','Oil and gold spike'],['2026-02-28',0,'Iran war and Strait of Hormuz crisis (ongoing)','Oil spike toward $120 (Brent); US blockade of Iranian ports 13 Apr–29 May; NGX gains in 2026'],['2026-03-01',0,'','']].filter(e=>e[2]);
const col={spot:'#2251FF',futures:'#051C2C',stocks:'#00A9F4',ngx:'#12805C'};
const gantt=()=>{const W=690,L=116,T0=58,rh=15,x0=+new Date('2020-01-01'),x1=+new Date('2027-01-01'),X=d=>L+(+new Date(d)-x0)/(x1-x0)*(W-L-8),as=[...D.ACCOUNTS].sort((a,b)=>a.startDate<b.startDate?-1:1),H=T0+as.length*rh+22,B=as.length*rh;
 let s=`<rect x="${X('2021-01-01')}" y="${T0-6}" width="${X('2023-01-01')-X('2021-01-01')}" height="${B+6}" fill="#F0F3F7"/><text x="${(X('2021-01-01')+X('2023-01-01'))/2}" y="${T0+B/2}" text-anchor="middle" class="l m">No participation, 2021–22</text>`;
 for(let y=2020;y<=2027;y++)s+=`<line x1="${X(y+'-01-01')}" x2="${X(y+'-01-01')}" y1="${T0-6}" y2="${T0+B}" stroke="#D5DCE4"/>`+(y<2027?`<text x="${X(y+'-07-01')}" y="${H-6}" text-anchor="middle" class="l">${y}</text>`:'');
 EV.forEach((e,i)=>{const x=X(e[0]),y=12+(i%2)*17;s+=`<line x1="${x}" x2="${x}" y1="${y}" y2="${T0-6}" stroke="#9AA9B8" stroke-dasharray="2 2"/>`+(e[1]?`<rect x="${x}" y="${T0-9}" width="${Math.max(X(e[1])-x,2)}" height="3" fill="#00A9F4"/>`:'')+`<circle cx="${x}" cy="${y}" r="7" fill="#051C2C"/><text x="${x}" y="${y+3}" text-anchor="middle" class="v w" style="font-size:8px">${i+1}</text>`});
 as.forEach((a,i)=>{const y=T0+i*rh,x=X(a.startDate),w=Math.max(X(a.endDate||'2026-09-24')-x,3);s+=`<text x="${L-6}" y="${y+10}" text-anchor="end" class="l">${a.shortName}</text><rect x="${x}" y="${y+2}" width="${w}" height="9" rx="1" fill="${col[a.market]}"/>`+(a.endDate?'':`<text x="${x-4}" y="${y+10}" text-anchor="end" class="l m">active</text>`)});
 return svg(W,H,s)};
const T=(c,r,x='')=>`<table class="${x}"><thead><tr>${c.map((h,i)=>`<th${i?' class="r"':''}>${h}</th>`).join('')}</tr></thead><tbody>${r.map(q=>`<tr${q.t?' class="tot"':''}>${(q.t?q.t:q).map((h,i)=>`<td${i?' class="r"':''}>${h}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
let pg=0;const page=(sec,title,body)=>{pg++;return`<section class="page"><div class="hd"><span>${sec}</span></div><h2>${title}</h2>${body}<div class="ft"><span>Financial market participation 2020, 2023–2026 · <span data-name>${NAME}</span> · <span data-date>${DATE}</span></span><span>${pg+1}</span></div></section>`};
const SRCTXT=`Source: FIBAM portfolio package v11, NGX source workbook, family credit and repayment log. Data as of ${ASOF}.`;
const usP=(reg('US')/cap),glP=(reg('Global')/cap),ngP=(reg('NGX')/cap);
const P=[];
P.push(`<section class="page cover"><div><div class="rule"></div><h1>Financial market participation 2020, 2023–2026</h1><p>How capital from personal, friend and family sources was deployed across FX, futures, equities, commodities, metals and crypto, what it returned, and what has flowed back.</p></div><div><div class="who" data-name>${NAME}</div><p>FIBAM · MXET Services<br>Data as of ${ASOF}</p></div></section>`);
P.push(page('Summary',`Seven years, ${D.ACCOUNTS.length} accounts: the prop-firm route cost ${usd(fees)} in fees, while the two equity funds are the only positive results`,
`<div class="kpis"><div><b>${D.ACCOUNTS.length}</b><span>accounts, 2020 to ${ASOF.slice(3)}</span></div><div><b>${usd(cap)}</b><span>capital deployed in markets</span></div><div><b>${f(nTr)}</b><span>trades logged</span></div><div><b>${sg(overall)}</b><span>net result on a cash basis</span></div></div>
<h3>What the record shows</h3>
<p><b>Participation came in three waves.</b> A first personal account in the COVID crash (2020), a two-year pause, then personal and prop-firm accounts in 2023–24, and since 2025 the equity funds plus a second prop campaign in 2026.</p>
<p><b>Most capital came from others.</b> Of ${usd(cap)} deployed, ${pc(grp('Personal')/cap)} was personal, ${pc(grp('Friend')/cap)} came from friends and ${pc(grp('Family')/cap)} from family. ${pc(usP)} went into US instruments, ${pc(glP)} into global FX and ${pc(ngP)} into Nigerian equities.</p>
<p><b>Prop evaluations were the costly way in.</b> ${prop.length} evaluations cost ${usd(fees)} in fees; ${passed} stages were passed and no payout has been received. Their ${usd(evPnl)} of account-level losses (${pcs(evPnl/capSz)} of ${usd(capSz)} of account size) was never personal capital, so this report counts the fee, not the notional loss, as the cash cost.</p>
<p><b>The equity funds are the positive strand.</b> 1kHooD earned ${sg(kh.pnl)} on ${usd(1000)} (${pc(kh.pnl/1000)}). NGX earned ${ngn(ngxN)} net of fees on ₦150,000 (${pc(ngxN/150000)}).</p>
<p><b>Little has flowed back as capital.</b> ₦400,000 of ${'₦720,000'} has been repaid to one family lender; 1kHooD has distributed ${usd(wU)} in distributions to the general partner and to TA, its limited partner.</p>
<h3>Net cash result by year (USD)</h3>${dbar(yrs.map(y=>({l:String(y),v:net(y)})),{lw:60,rh:20})}<p>The cumulative result bottomed at ${usd(cum[2])} at the end of 2024 and stood at ${usd(cum[4])} by ${ASOF.slice(3)}. The 2025–26 gains come from the two equity funds; the prop route still cost ${usd(Y[2026].fee)} in fees in 2026.</p>
<div class="note">Results are shown on a cash basis: personal-account outcomes, prop-firm fees, and fund trading results. Evaluation-account P&amp;L is reported separately as a memo item.</div>`,SRCTXT));
P.push(page('1 · Timeline',`Participation came in three waves, separated by a two-year gap`,`<div class="lg"><span><i style="background:#2251FF"></i>Spot FX and CFDs</span><span><i style="background:#051C2C"></i>US futures</span><span><i style="background:#00A9F4"></i>US equities</span><span><i style="background:#12805C"></i>Nigerian equities</span><span><i style="background:#00A9F4;height:1mm"></i>Event with duration</span></div>${gantt()}
<p style="margin-top:4mm"><b>2020.</b> One personal FX account, opened as COVID volatility peaked. <b>2023–24.</b> A second personal account, then nine prop evaluations in FX and index futures. <b>2025 onward.</b> The 1kHooD and NGX funds start, a further six evaluations run in 2026, and both funds are still active. Numbered markers refer to the events on the next page.</p>`,SRCTXT));
P.push(page('1 · Timeline',`Each phase of participation overlapped a major macro or geopolitical shock`,T(['#','Period','Event','Relevance to the markets traded'],EV.map((e,i)=>{const d=x=>new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});return[i+1,e[1]?`${d(e[0])} – ${d(e[1])}`:d(e[0]),e[2],e[3]]}).map(r=>r.map((c,i)=>i?c:c)),'ev')+`<p style="font-size:8pt;color:#5B6B7A">Dates for 2026 events are from public reporting as of ${ASOF}; the Hormuz crisis is ongoing.</p>`,SRCTXT+' Event dates: public sources.'));
const mk=rows.map(r=>[r.k,r.rg,f(r.n),r.acc?sg(r.acc):'–',r.fund?sg(r.fund):'–']);
P.push(page('2 · Markets',`${pc(usP)} of capital went to US markets and ${pc(glP)} to global FX; Nigerian equities are a small third leg`,
`<h3>By region, share of capital deployed</h3>${stack([{l:'US',v:reg('US'),c:'#051C2C'},{l:'Global',v:reg('Global'),c:'#2251FF'},{l:'NGX',v:reg('NGX'),c:'#12805C'}])}
<h3>By market type</h3>${T(['Market type','Region','Trades','Prop and personal accounts','Funds'],[...mk,{t:['Total','',f(nTr),sg(sum(rows.map(r=>r.acc))),sg(sum(rows.map(r=>r.fund)))]}])}
<p>US covers futures, equity index CFDs and the 1kHooD stock portfolio. Global covers FX, commodities, metals and crypto, all traded through contracts for difference (CFDs), which track a price without owning the asset. Crypto is four BTCUSD trades in one 2024 evaluation. “Prop and personal accounts” shows account-level results, including evaluation accounts, so it should not be read as cash lost. Funds are 1kHooD (USD) and NGX (converted to USD at prevailing monthly rates).</p>`,SRCTXT));
const pf=['MyFundedFutures','MyFundedFX','FundedNext','The5ers'].map(n=>{const s=prop.filter(a=>a.platform===n);return{n,c:s.length,fee:sum(s.map(a=>a.costOfFund)),sz:sum(s.map(a=>a.size)),ev:sum(s.map(a=>a.pnl)),ok:s.filter(a=>a.pnl>0).length}});
P.push(page('3 · Entry paths',`Prop evaluations were the costliest way in: ${prop.length} attempts, ${passed} stages passed, no payouts`,
T(['Entry path','Accounts','Capital deployed','Cash result','Status'],[['Retail investing (personal accounts)',`3: Alpari 2020, Alpari 2023, NGX brokerage`,usd(829.61),sg(persPnl+ngxU),'Alpari closed; NGX active'],['Prop firms',`${prop.length}: four firms`,usd(fees),sg(-fees),'All closed; 0 payouts'],['Managed portfolio (1kHooD)','1: Robinhood, general and limited partner',usd(1000),sg(kh.pnl),'Active'],{t:['Total',String(D.ACCOUNTS.length),usd(cap),sg(overall),'']}])+
`<h3>Prop firms: fees paid and account-level results</h3>${T(['Firm','Accounts','Account size','Fees paid','Account-level P&amp;L','% of size','Stages passed'],pf.map(p=>[p.n,p.c,usd(p.sz),usd(p.fee,2),sg(p.ev),pcs(p.ev/p.sz),p.ok]))}
<h3>Evaluation fees by firm</h3>${dbar(pf.map(p=>({l:p.n,v:p.fee,c:'#051C2C'})),{lw:130})}
<p style="margin-top:3mm">Fees of ${usd(fees)} bought access to ${usd(capSz)} of account capacity across ${prop.length} accounts (${f(fees/capSz*100,2)}%). Three of the five MyFundedFutures evaluations ended at about −4% ($2,000 each), consistent with a fixed drawdown limit. Retail accounts are self-directed personal accounts. The managed path is 1kHooD, a fund run as general partner with TA as the limited partner. The two stages passed were both at The5ers in May 2026; the funded account that followed was closed after one day.</p>`,SRCTXT));
P.push(page('4 · Funding',`Friends and family supplied ${pc((grp('Friend')+grp('Family'))/cap)} of the ${usd(cap)} deployed; personal capital was ${pc(grp('Personal')/cap)}`,
`<h3>Capital deployed by source</h3>${stack(SRC.map(s=>({l:s,v:fs_[s],c:SC[s]})))}
<div class="lg" style="margin-top:2mm"><span>IF: personal</span><span>TA, PO: friends (TA a close friend; PO contributed in 2020 only)</span><span>MO, BA: family</span></div>
<h3>Where each source went (USD)</h3>${T(['Destination','IF','PO','TA','MO','BA','Total'],[...F.map(r=>[r[0],...SRC.map(s=>r[3][s]?f(r[3][s],2):'–'),f(sum(Object.values(r[3])),2)]),{t:['Total',...SRC.map(s=>f(fs_[s],2)),f(cap,2)]}])}
<p>Any funding not explicitly attributed to a source is treated as personal (IF). BA’s ₦442,500 for futures costs is $295 at ₦1,500/$; its ₦150,000 into NGX is recorded as $107.64.</p>
<h3>Received versus deployed (family, ₦)</h3>${T(['Source','Received','Deployed in markets','Into operations'],[['MO (₦420,000 investment, ₦300,000 loan)','₦720,000','≈ ₦398,000','≈ ₦322,000'],['BA','₦1,000,000','₦592,500','₦407,500']])}`,SRCTXT+' Family amounts in naira as recorded.'));
P.push(page('5 · Return of capital',`Repayments have gone to one family lender so far; 1kHooD distributes to its partners`,
`<h3>Repayments to MO (₦)</h3>${dbar([{l:'Received',v:720000,c:'#8A97A5'},{l:'Repaid to date',v:400000,c:'#12805C'},{l:'Outstanding',v:320000,c:'#B3261E'}],{fmt:ngn,lw:110})}
${T(['Date','Repaid','Outstanding'],[['17 May 2024','₦100,000','₦620,000'],['7 Jul 2024','₦200,000','₦420,000'],['9 Oct 2024','₦100,000','₦320,000']])}
<p style="font-size:8pt;color:#5B6B7A">Outstanding shown in payment order; the source log lists the 9 Oct 2024 payment first.</p>
<h3>1kHooD: capital, profit and distributions (USD)</h3>${dbar([{l:'Capital contributed (TA, limited partner)',v:1000,c:'#8A97A5'},{l:'Cumulative trading P&L',v:kh.pnl},{l:'Distributed to general partner',v:gpU,c:'#051C2C'},{l:'Distributed to TA (limited partner)',v:lpU,c:'#2251FF'},{l:'Implied balance remaining',v:implied,c:'#8A97A5'}],{lw:215})}
<div class="note">${wd.length} withdrawals total ${usd(wU,2)} since Sep 2025, split by the fund’s general and limited partner shares in GBP (${f(gpG/(gpG+lpG)*100)}% and ${f(lpG/(gpG+lpG)*100)}%). They exceed cumulative trading profit of ${usd(kh.pnl,2)}, so they include a partial return of contributed capital; the implied balance is ${usd(implied,2)}.</div>
${T(['Source','Nature of return','Status'],[['IF (personal)','None expected','–'],['PO, TA (friends)','TA: distributions as limited partner in 1kHooD. PO: none','TA receiving; PO none'],['MO (family)','Repayment of credit','₦400,000 of ₦720,000'],['BA (family)','Repayment target','None yet']])}
<p>Returning capital to every source remains a stated target for the journey.</p>`,SRCTXT));
const yt=yrs.map(y=>[y,sg(Y[y].p),sg(-Y[y].fee),sg(Y[y].kh),sg(Y[y].ng),sg(net(y)),sg(Y[y].ev)]);
P.push(page('6 · Performance',`Losses were concentrated in 2024; 2025 and 2026 both finished net positive on a cash basis`,
`<h3>By year (USD, cash basis)</h3>${T(['Year','Personal accounts','Prop fees','1kHooD','NGX','Net result','Memo: evaluation P&amp;L'],[...yt,{t:['Total',sg(persPnl),sg(-fees),sg(kh.pnl),sg(ngxU),sg(overall),sg(evPnl)]}])}
<h3>By entry path</h3>${dbar([{l:'Retail (personal accounts and NGX)',v:persPnl+ngxU},{l:'Prop firms (fees)',v:-fees},{l:'Managed (1kHooD)',v:kh.pnl}],{lw:200})}
<h3>By market type, account-level result including evaluation accounts</h3>${dbar(rows.map(r=>({l:r.k,v:r.acc+r.fund})),{lw:130,rh:19})}
<p style="margin-top:3mm"><b>Overall:</b> ${sg(overall)} on ${usd(cap)} deployed (${pc(overall/cap)}). <b>Status:</b> ${D.ACCOUNTS.filter(a=>a.status==='completed').length} accounts closed, 2 active. NGX in naira: ${ngn(ngxG)} gross, ${ngn(ngxF)} fees, ${ngn(ngxN)} net across ${ngx.length} closed trades.</p><div class="note"><b>Equity funds, both active.</b> 1kHooD: ${sg(kh.pnl)} on ${usd(1000)} (${pc(kh.pnl/1000)}), with ${usd(wU)} distributed to its partners. NGX: ${ngn(ngxN)} net on ₦150,000 (${pc(ngxN/150000)}) across ${ngx.length} closed trades.</div>`,SRCTXT));
P.push(page('7 · Research approach',`Pattern recognition is the core thesis; trades per evaluation fell from ${avg('2024')} in 2024 to ${avg('2026')} in 2026`,
`<p><b>Primary approach.</b> Generating value from the markets through the application of the art, science and technology of pattern recognition.</p>
<div class="cols"><div><h3>Art</h3><p>Reading structure, context and behaviour in price: the discretionary judgement of what a pattern means now.</p></div><div><h3>Science</h3><p>Testing whether a pattern repeats with an edge: samples, expectancy and risk limits rather than anecdote.</p></div><div><h3>Technology</h3><p>Encoding what works into indicators, dashboards and automated systems so it can be applied without drift.</p></div></div>
<h3>Supporting lenses</h3>${T(['Lens','Role'],[['Technicals','Structure, levels, momentum and mean-reversion signals across FX, futures and stocks'],['Fundamentals','Sector and company selection for the equity funds, including thematic sector intelligence'],['Events','Macro and geopolitical catalysts: rates, elections, wars, supply shocks (see events, page 4)']])}
<h3>Evidence from the record</h3>
<p>Evaluations in 2024 averaged ${avg('2024')} trades each, and the largest reached ${Math.max(...prop.map(a=>a.trades))}; in 2026 they averaged ${avg('2026')}. Measured against account size, the ${c24.n} evaluations of 2024 ended ${pcs(c24.pl/c24.sz)} and the ${c26.n} of 2026 ended ${pcs(c26.pl/c26.sz)}; ${c24.up} of ${c24.n} finished positive in 2024 and ${c26.up} of ${c26.n} in 2026. The samples are small and the firms, account sizes and instruments differ, so this is indicative rather than proof. The equity funds are the profitable strand.</p>
<h3>Tooling built along the way</h3><p>Rule-based systems and dashboards are part of the approach: automated trading rules for two trading platforms, an intraday mean-reversion engine, charting indicators, and a sector-intelligence tool.</p>`,SRCTXT));
P.push(page('Notes',`Basis of preparation`,
`<p><b>Cash basis.</b> Personal accounts show cash result; prop firms show the evaluation fee paid; funds show trading result before the general and limited partner split. Evaluation-account P&amp;L is memo only.</p>
<p><b>Currency.</b> Reported in USD. NGX is naira-denominated in source and converted to USD at approximate monthly ₦/$ levels: recorded rates for 2024 and CBN NFEM levels for 2025–26 (about ₦1,360–1,530). Family amounts are shown in naira as recorded.</p>
<p><b>NGX.</b> Trade gains in the source are gross; fees are deducted here. One open position (6 Geregu shares) is unrealised and excluded. The source sheet’s total gain (₦110,719) sits ₦778 below the trade-level total because three July 2025 rows carry an open mark rather than the exit price.</p>
<p><b>Data gaps.</b> Alpari 2020 predates detailed trade records (account-level only). MyFundedFX #2 is partly summarised, MyFundedFX #4 comes from the firm’s performance report, and Alpari 2023 uses cash result (−$324.93) rather than the trade record (−$284.73).</p>
<p><b>Funding rule.</b> Unattributed funding is personal. No prop payouts, no other accounts, and no participation in 2021–22.</p>
<p><b>Sources.</b> FIBAM portfolio records (account and trade-level data), NGX trade records, and the family credit and repayment log. Event dates are from public reporting. Data as of ${ASOF}.</p>
<p><b>Terms.</b> A prop firm is a proprietary trading firm that lets a trader use its account after passing a paid evaluation. A CFD is a contract for difference, which tracks a price without owning the asset. In 1kHooD, the general partner runs the fund and the limited partner provides the capital.</p>`,SRCTXT));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Financial market participation 2020, 2023–2026 · ${NAME}</title><link rel="stylesheet" href="assets/report.css"><script>
/* To change the name or date shown throughout the report, edit the two values below. */
var REPORT={name:"${NAME}",date:"${DATE}"};
</script></head><body><div class="bar"><span>Financial market participation 2020, 2023–2026</span><a href="${PDF}" download data-pdf-name="${NAME}">Download PDF</a></div>${P.join('\n')}<script>(function(){var q=function(s){return document.querySelectorAll(s)};
q('[data-name]').forEach(function(e){e.textContent=REPORT.name});q('[data-date]').forEach(function(e){e.textContent=REPORT.date});
document.title='Financial market participation 2020, 2023–2026 · '+REPORT.name;
var a=q('.bar a')[0];if(REPORT.name!==a.getAttribute('data-pdf-name')){a.addEventListener('click',function(ev){ev.preventDefault();window.print()})}
document.documentElement.style.setProperty('--z',Math.min(1,innerWidth/800))})()</script></body></html>`;
fs.writeFileSync(R+'/index.html',html);
console.log(JSON.stringify({cap,fs_,overall:+overall.toFixed(2),ngxU:+ngxU.toFixed(2),ngxN,fees,persPnl,evPnl,passed,nTr,net:yrs.map(y=>+net(y).toFixed(1)),wU,lpU:+lpU.toFixed(1),implied:+implied.toFixed(2),avg24:avg('2024'),avg26:avg('2026'),rows:rows.map(r=>[r.k,r.n,+r.acc.toFixed(0),+r.fund.toFixed(0)])}));
