// node tools/build-public.mjs  ->  overview.html  (then: node tools/make-pdf-public.cjs)
import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const D=new Function(fs.readFileSync(R+'/tools/data.js','utf8').replace("'use strict';",'')+';return {ACCOUNTS,TRADE_DATA,KHOOD_TRADES,NGX_TRADES}')();
const VER='1.0.0',ASOF='September 2026',NAME='Foabao',DATE='September 2026',PDF='Foabao-Financial-Market-Participation-2023-2026-Overview.pdf';
const sum=a=>a.reduce((s,x)=>s+x,0),f=(n,d=0)=>n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const usd=(n,d=0)=>(n<0?'−':'')+'$'+f(Math.abs(n),d),sg=(n,d=0)=>`<span class="${n<0?'neg':'pos'}">${n<0?'−':'+'}$${f(Math.abs(n),d)}</span>`,ngn=n=>(n<0?'−':'')+'₦'+f(Math.abs(n)),pc=n=>f(n*100)+'%';
const FX=[['2024-05-29',1393],['2024-07-05',1530],['2025-02-27',1530],['2025-07-15',1530],['2025-08-28',1510],['2025-10-24',1455],['2026-01-09',1445],['2026-03-25',1380],['2026-05-15',1362],['2026-09-18',1364]];
const rate=d=>{const t=+new Date(d);for(let i=1;i<FX.length;i++){const a=+new Date(FX[i-1][0]),b=+new Date(FX[i][0]);if(t<=b)return t<=a?FX[i-1][1]:FX[i-1][1]+(FX[i][1]-FX[i-1][1])*(t-a)/(b-a)}return FX.at(-1)[1]};
const cls=i=>{i=(i||'').split(',')[0].trim().toUpperCase();if(/^(M?NQ|M?ES|M?YM)[FGHJKMNQUVXZ]\d$/.test(i))return'Futures';if(/WTI|XTI|CRUDE/.test(i))return'Commodities';if(/^(XA|A)[UG][A-Z]{3}$/.test(i))return'Metals';if(/BTC|ETH/.test(i))return'Crypto';if(/^(SPX|SP500|NAS100)/.test(i))return'Equities';if(/^[A-Z]{6}$/.test(i))return'FX';return null};
// ── anonymised names: no real broker or prop-firm names in this version
const FN={MyFundedFutures:'Futures prop firm A',MyFundedFX:'FX prop firm A',FundedNext:'Index prop firm A',The5ers:'Index prop firm B'};
// ── data — 2020 excluded from every total, table and chart in this version; it appears once, briefly, in prose only
const A=D.ACCOUNTS.filter(a=>a.id!=='NGX'&&a.id!=='ALPARI-2020'),prop=A.filter(a=>a.type.startsWith('prop')),pers=A.filter(a=>a.type==='personal'),kh=A.find(a=>a.id==='1KHOOD');
const ngx=D.NGX_TRADES.filter(t=>!t.open).map(t=>({...t,usd:(t.netPnl-t.fees)/rate(t.closeDate)}));
const ngxG=sum(ngx.map(t=>t.netPnl)),ngxF=sum(ngx.map(t=>t.fees)),ngxN=ngxG-ngxF,ngxU=sum(ngx.map(t=>t.usd));
const ngxCap=220792.93,ngxCapUSD=158.87; // derived from the trade record itself; see Notes
const fees=sum(prop.map(a=>a.costOfFund)),persPnl=sum(pers.map(a=>a.pnl)),evPnl=sum(prop.map(a=>a.pnl)),passed=prop.filter(a=>a.pnl>0).length;
const overall=persPnl-fees+kh.pnl+ngxU;
const rows=[['Futures','US'],['Equity indices (CFDs)','US'],['US equity','US'],['Nigerian equity','Nigeria'],['FX','Global'],['Commodities','Global'],['Metals','Global'],['Crypto','Global']].map(([k,rg])=>({k,rg,n:0,acc:0,fund:0}));
const row=k=>rows.find(x=>x.k===k),mp={Futures:'Futures',Equities:'Equity indices (CFDs)',FX:'FX',Commodities:'Commodities',Metals:'Metals',Crypto:'Crypto'};
for(const a of A){if(a.id==='1KHOOD')continue;const def=a.id.startsWith('MFFU')?'Futures':'FX';let s=0;for(const t of D.TRADE_DATA[a.id]||[]){const p=t.netPnl||0,sm=/SUMMARY|REMAIN/i.test(t.instrument||''),x=row(mp[(!sm&&cls(t.instrument))||def]);if(!sm)x.n++;x.acc+=p;s+=p}row(mp[def]).acc+=a.pnl-s}
row('US equity').n=D.KHOOD_TRADES.length;row('US equity').fund=kh.pnl;row('Nigerian equity').n=ngx.length;row('Nigerian equity').fund=ngxU;
const nTr=sum(rows.map(r=>r.n));
const yrs=[2023,2024,2025,2026],Y=Object.fromEntries(yrs.map(y=>[y,{p:0,fee:0,kh:0,ng:0}]));
for(const a of pers)Y[a.endDate.slice(0,4)].p+=a.pnl;for(const a of prop){Y[a.startDate.slice(0,4)].fee+=a.costOfFund}
for(const t of D.KHOOD_TRADES)Y[t.closeDate.slice(0,4)].kh+=t.netPnl;for(const t of ngx)Y[t.closeDate.slice(0,4)].ng+=t.usd;
const net=y=>Y[y].p-Y[y].fee+Y[y].kh+Y[y].ng;
const capSz=sum(prop.map(a=>a.size)),pcs=x=>(x<0?'−':'+')+f(Math.abs(x)*100,1)+'%',sp=x=>`<span class="${x<0?'neg':'pos'}">${pcs(x)}</span>`;
const coh=t=>{const q=prop.filter(a=>t(a.startDate));return{n:q.length,sz:sum(q.map(a=>a.size)),pl:sum(q.map(a=>a.pnl)),up:q.filter(a=>a.pnl>0).length}},c24=coh(d=>d<'2025'),c26=coh(d=>d>'2025');
const capOf=a=>a.id==='NGX'?ngxCapUSD:a.type.startsWith('prop')?a.costOfFund:a.size,inPlay=y=>sum(D.ACCOUNTS.filter(a=>a.id!=='ALPARI-2020'&&+a.startDate.slice(0,4)<=y&&(a.endDate?+a.endDate.slice(0,4):2026)>=y).map(capOf));
const cap=sum(D.ACCOUNTS.filter(a=>a.id!=='ALPARI-2020').map(capOf));
const mi=s=>(+s.slice(0,4)-2020)*12+(+s.slice(5,7)-1),MON=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],mn=i=>MON[i%12]+' '+(2020+Math.floor(i/12)),N=mi('2026-09-30')+1;
const cumM=(ev,from=0)=>{const d=new Array(N).fill(0);ev.forEach(([m,v])=>{d[m]+=v});let c=0;const o=[];d.forEach((x,i)=>{c+=x;if(i>=from)o.push([i,c])});return o};
const routeOf=a=>a.type==='personal'?'Personal':a.type.startsWith('prop')?'Prop':'Fund',RC={Personal:'#051C2C',Prop:'#2251FF',Fund:'#12805C'};
const acc23=D.ACCOUNTS.filter(a=>a.id!=='ALPARI-2020');
const cashS23=cumM([...pers.map(a=>[mi(a.endDate),a.pnl]),...prop.map(a=>[mi(a.startDate),-a.costOfFund]),...D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl]),...ngx.map(t=>[mi(t.closeDate),t.usd])]);
const capCumM23=cumM(acc23.map(a=>[mi(a.startDate),capOf(a)])),roiS23=[];for(let i=mi('2023-09-11');i<N;i++)if(capCumM23[i][1]>0)roiS23.push([i,cashS23[i][1]/capCumM23[i][1]*100]);
const ngS=cumM(ngx.map(t=>[mi(t.closeDate),(t.netPnl-t.fees)/1500]),mi('2024-05-01')),khS=cumM(D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl/10]),mi('2025-02-01')),khU=cumM(D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl]),mi('2025-02-01'));
const avg=y=>{const s=prop.filter(a=>a.startDate.startsWith(y)&&a.trades>0);return Math.round(sum(s.map(a=>a.trades))/s.length)};
// ── charts
const svg=(w,h,b)=>`<svg viewBox="0 0 ${w} ${h}" role="img">${b}</svg>`;
const dbar=(rs,{w=690,lw=185,fmt=usd,rh=22}={})=>{const pad=66,v=rs.map(r=>r.v),mn=Math.min(0,...v),mx=Math.max(0,...v),sc=(w-lw-pad*2)/((mx-mn)||1),z=lw+pad-mn*sc;
 return svg(w,rs.length*rh+6,`<line x1="${z}" x2="${z}" y1="0" y2="${rs.length*rh+3}" stroke="#8A97A5"/>`+rs.map((r,i)=>{const y=i*rh+3,bw=Math.abs(r.v)*sc,x=r.v<0?z-bw:z;return`<text x="0" y="${y+13}" class="l">${r.l}${r.l2?`<tspan class="m"> ${r.l2}</tspan>`:''}</text><rect x="${x}" y="${y+2}" width="${Math.max(bw,1)}" height="${rh-9}" fill="${r.c||(r.v<0?'#B3261E':'#2251FF')}"/><text x="${r.v<0?x-4:x+bw+4}" y="${y+13}" text-anchor="${r.v<0?'end':'start'}" class="v">${fmt(r.v)}</text>`}).join(''))};
const mono=P=>{const n=P.length,d=[],m=[];for(let i=0;i<n-1;i++)d[i]=(P[i+1][1]-P[i][1])/(P[i+1][0]-P[i][0]);m[0]=d[0];m[n-1]=d[n-2];for(let i=1;i<n-1;i++)m[i]=d[i-1]*d[i]<=0?0:(d[i-1]+d[i])/2;
 for(let i=0;i<n-1;i++){if(d[i]===0){m[i]=m[i+1]=0}else{const a=m[i]/d[i],b=m[i+1]/d[i],h=Math.hypot(a,b);if(h>3){const t=3/h;m[i]=t*a*d[i];m[i+1]=t*b*d[i]}}}
 let s=`M${P[0][0]},${P[0][1]}`;for(let i=0;i<n-1;i++){const dx=(P[i+1][0]-P[i][0])/3;s+=`C${P[i][0]+dx},${P[i][1]+m[i]*dx} ${P[i+1][0]-dx},${P[i+1][1]-m[i+1]*dx} ${P[i+1][0]},${P[i+1][1]}`}return s};
let gi=0;
const area=({ss,x0,x1,y0,y1,st,fmt=usd,H=200,bands=[],marks=[]})=>{const W=690,L=54,R=18,T=14,B=26,id='g'+(gi++),X=m=>L+(m-x0)/(x1-x0)*(W-L-R),Y=v=>T+(y1-v)/(y1-y0)*(H-T-B),zb=Y(Math.min(Math.max(0,y0),y1)),PT=q=>q.pts.map(([m,v])=>[X(m),Y(v)]);
 let s='<defs>'+ss.map((q,k)=>`<linearGradient id="${id}${k}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${q.c}" stop-opacity="${q.neg?0.04:0.34}"/><stop offset="1" stop-color="${q.c}" stop-opacity="${q.neg?0.34:0.04}"/></linearGradient>`).join('')+'</defs>';
 bands.forEach(b=>{s+=`<rect x="${X(b[0])}" y="${T}" width="${X(b[1])-X(b[0])}" height="${H-T-B}" fill="#F0F3F7"/><text x="${(X(b[0])+X(b[1]))/2}" y="${T+11}" text-anchor="middle" class="l m">${b[2]}</text>`});
 for(let v=Math.ceil(y0/st)*st;v<=y1+1e-9;v+=st)s+=`<line x1="${L}" x2="${W-R}" y1="${Y(v)}" y2="${Y(v)}" stroke="${v===0?'#8A97A5':'#E3E9EF'}"/><text x="${L-6}" y="${Y(v)+3}" text-anchor="end" class="l m">${fmt(v)}</text>`;
 for(let y=2023;y<=2027;y++){const m=(y-2020)*12;if(m>=x0-0.5&&m<x1)s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${T}" y2="${H-B}" stroke="#E3E9EF" stroke-dasharray="2 3"/><text x="${X(m)+3}" y="${H-9}" class="l m">${y}</text>`}
 ss.forEach((q,k)=>{const P=PT(q);s+=`<path d="${mono(P)}L${P.at(-1)[0]},${zb}L${P[0][0]},${zb}Z" fill="url(#${id}${k})"/>`});
 ss.forEach(q=>{s+=`<path d="${mono(PT(q))}" fill="none" stroke="${q.c}" stroke-width="2" stroke-linejoin="round"/>`});
 marks.forEach(k=>{s+=`<circle cx="${X(k.m)}" cy="${Y(k.v)}" r="3.6" fill="${k.c||'#051C2C'}" stroke="#fff" stroke-width="1.5"/><text x="${X(k.m)+(k.dx||0)}" y="${Y(k.v)+(k.dy||0)}" text-anchor="${k.a||'middle'}" class="v">${k.t}</text>`});
 return svg(W,H,s)};
const journeyChart=()=>{const W=690,L=54,R=18,T=16,B=52,H=230,plotH=H-T-B,x0=mi('2023-09-11'),x1=80,y0=-90,y1=10,st=20,X=m=>L+(m-x0)/(x1-x0)*(W-L-R),Y=v=>T+(y1-v)/(y1-y0)*plotH;
 let s='<defs><linearGradient id="jg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2251FF" stop-opacity="0.05"/><stop offset="1" stop-color="#2251FF" stop-opacity="0.32"/></linearGradient></defs>';
 for(let v=Math.ceil(y0/st)*st;v<=y1+1e-9;v+=st)s+=`<line x1="${L}" x2="${W-R}" y1="${Y(v)}" y2="${Y(v)}" stroke="${v===0?'#8A97A5':'#E3E9EF'}"/><text x="${L-6}" y="${Y(v)+3}" text-anchor="end" class="l m">${v}%</text>`;
 for(let y=2023;y<=2027;y++){const m=(y-2020)*12;if(m>=x0-0.5&&m<=x1)s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${T}" y2="${T+plotH}" stroke="#E3E9EF" stroke-dasharray="2 3"/><text x="${X(m)+3}" y="${T+plotH+11}" class="l m">${y}</text>`}
 const P=roiS23.map(([m,v])=>[X(m),Y(v)]),zY=Y(0);
 s+=`<path d="${mono(P)}L${P.at(-1)[0]},${zY}L${P[0][0]},${zY}Z" fill="url(#jg)"/><path d="${mono(P)}" fill="none" stroke="#2251FF" stroke-width="2" stroke-linejoin="round"/>`;
 const tb=T+plotH+24;
 acc23.forEach(a=>{const m=mi(a.startDate);if(m<x0-0.5||m>x1)return;const h=Math.max(2,Math.sqrt(capOf(a))*0.7);s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${tb}" y2="${tb-h}" stroke="${RC[routeOf(a)]}" stroke-width="2"/>`});
 s+=`<line x1="${L}" x2="${W-R}" y1="${tb}" y2="${tb}" stroke="#D5DCE4"/><text x="${L}" y="${tb+12}" class="l m">Each mark is one account at its start date; taller marks committed more capital</text>`;
 const last=roiS23.at(-1);s+=`<circle cx="${X(80)}" cy="${Y(last[1])}" r="3.6" fill="#051C2C" stroke="#fff" stroke-width="1.5"/><text x="${X(80)-8}" y="${Y(last[1])-9}" text-anchor="end" class="v">${pcs(last[1]/100)}, Sep 2026</text>`;
 return svg(W,H,s)};
const MT={'US futures':sum(prop.filter(a=>a.platform==='MyFundedFutures').map(a=>a.costOfFund)),'US equity':1000,'Nigerian equity':ngxCapUSD};
MT['Global FX and CFDs']=cap-MT['US futures']-MT['US equity']-MT['Nigerian equity'];
const MC={'Global FX and CFDs':['#2251FF','Global'],'US equity':['#00A9F4','US'],'US futures':['#051C2C','US'],'Nigerian equity':['#12805C','Nigeria']};
const pie=()=>{const ps=Object.entries(MT).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({k,v,c:MC[k][0],rg:MC[k][1]})),t=sum(ps.map(p=>p.v)),cx=105,cy=100,R=90,r=56,P=(d,g)=>[cx+d*Math.cos(g),cy+d*Math.sin(g)];let a=-Math.PI/2,s='';
 ps.forEach((p,i)=>{const b=a+p.v/t*2*Math.PI,[x1,y1]=P(R,a),[x2,y2]=P(R,b),[x3,y3]=P(r,b),[x4,y4]=P(r,a),lg=b-a>Math.PI?1:0;
  s+=`<path d="M${x1},${y1}A${R},${R} 0 ${lg} 1 ${x2},${y2}L${x3},${y3}A${r},${r} 0 ${lg} 0 ${x4},${y4}Z" fill="${p.c}" stroke="#fff" stroke-width="2"/>`;
  if(p.v/t>.1){const m=(a+b)/2,[tx,ty]=P((R+r)/2,m);s+=`<text x="${tx}" y="${ty+3}" text-anchor="middle" class="v w">${pc(p.v/t)}</text>`}
  const y=44+i*38;s+=`<rect x="262" y="${y-9}" width="10" height="10" fill="${p.c}"/><text x="280" y="${y}" class="v">${p.k}</text><text x="280" y="${y+13}" class="l m">${p.rg} · ${usd(p.v)}</text><text x="650" y="${y+6}" text-anchor="end" style="font:600 17px 'Source Serif 4',Georgia,serif;fill:#051C2C">${pc(p.v/t)}</text>`;a=b});
 s+=`<text x="${cx}" y="${cy-2}" text-anchor="middle" style="font:600 17px 'Source Serif 4',Georgia,serif;fill:#051C2C">${usd(t)}</text><text x="${cx}" y="${cy+13}" text-anchor="middle" class="l m">deployed</text>`;return svg(690,200,s)};
const EV=[['2022-02-24',0,'Russia–Ukraine war begins','Energy and grain shock; commodity and inflation repricing'],['2022-11-30',0,'ChatGPT released','Start of the AI investment cycle behind later US equity leadership'],['2023-03-10',0,'Silicon Valley Bank collapse','Regional-bank stress; rates repriced'],['2023-05-29','2023-06-14','Nigeria: subsidy removal and FX unification','Naira devalued; reshaped the cost of dollar capital'],['2023-10-07',0,'Israel–Hamas war begins','Oil and gold volatility; the personal account traded WTI and gold'],['2024-01-01','2024-02-29','Naira sell-off','Peak dollar cost for the year’s prop-firm evaluations'],['2024-08-05',0,'Yen carry-trade unwind','Sharp fall across markets during the futures evaluations'],['2024-09-18',0,'Fed begins cutting rates','Start of the easing cycle'],['2024-11-05',0,'US presidential election','Trend day for US indices and the dollar'],['2025-04-02',0,'US “Liberation Day” tariffs','Global equity sell-off and rebound; the US Equity Account’s first year'],['2025-06-13','2025-06-24','Israel–Iran 12-day war','Oil and gold spike'],['2026-02-28',0,'Iran war and Strait of Hormuz crisis (ongoing)','Oil spike toward $120 (Brent); US blockade of Iranian ports 13 Apr–29 May; Nigerian equity gains in 2026']];
const col={spot:'#2251FF',futures:'#051C2C',stocks:'#00A9F4',ngx:'#12805C'};
const lab=a=>{if(a.id==='NGX')return'Nigerian Equity Account';if(a.id==='1KHOOD')return'US Equity Account';if(a.type==='personal')return'Personal FX account';const q=D.ACCOUNTS.filter(x=>x.platform===a.platform&&x.type.startsWith('prop')).sort((x,y)=>x.startDate<y.startDate?-1:1);return FN[a.platform]+' '+(q.indexOf(a)+1)};
const gantt=()=>{const W=690,L=124,T0=18,rh=15,x0=+new Date('2023-01-01'),x1=+new Date('2027-01-01'),X=d=>L+(+new Date(d)-x0)/(x1-x0)*(W-L-8),as=[...acc23].sort((a,b)=>a.startDate<b.startDate?-1:1),H=T0+as.length*rh+22,B=as.length*rh;
 let s='';
 for(let y=2023;y<=2027;y++)s+=`<line x1="${X(y+'-01-01')}" x2="${X(y+'-01-01')}" y1="${T0-6}" y2="${T0+B}" stroke="#D5DCE4"/>`+(y<2027?`<text x="${X(y+'-07-01')}" y="${H-6}" text-anchor="middle" class="l">${y}</text>`:'');
 as.forEach((a,i)=>{const y=T0+i*rh,x=X(a.startDate),w=Math.max(X(a.endDate||'2026-09-24')-x,3);s+=`<text x="${L-6}" y="${y+10}" text-anchor="end" class="l">${lab(a)}</text><rect x="${x}" y="${y+2}" width="${w}" height="9" rx="1" fill="${col[a.market]}"/>`+(a.endDate?'':`<text x="${x-4}" y="${y+10}" text-anchor="end" class="l m">active</text>`)});
 return svg(W,H,s)};
const T=(c,r,x='')=>`<table class="${x}"><thead><tr>${c.map((h,i)=>`<th${i?' class="r"':''}>${h}</th>`).join('')}</tr></thead><tbody>${r.map(q=>`<tr${q.t?' class="tot"':''}>${(q.t?q.t:q).map((h,i)=>`<td${i?' class="r"':''}>${h}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
let pg=0;const page=(sec,title,body)=>{pg++;return`<section class="page"><div class="hd"><span>${sec}</span></div><h2>${title}</h2>${body}<div class="ft"><span>Financial market participation, 2023–2026 · <span data-name>${NAME}</span> · <span data-date>${DATE}</span></span><span>${pg+1}</span></div></section>`};
const SRCTXT=`Source: account and trade-level records; event dates from public reporting. Data as of ${ASOF}.`;
const P=[];
P.push(`<section class="page cover"><div><div class="rule"></div><h1>Financial market participation, 2023–2026</h1><p>Overview of activity across FX, futures, equities and related markets.</p></div><div><div class="who" data-name>${NAME}</div><p>${DATE}</p></div></section>`);
P.push(page('Summary',`Three years of activity across six markets, three paths`,
`<div class="kpis"><div><b>${usd(Math.floor(cap/100)*100)}+</b><span>capital deployed in markets</span></div><div><b>36</b><span>months of continuous activity</span></div><div><b>${f(Math.floor(nTr/100)*100)}+</b><span>trades logged</span></div><div><b>6</b><span>market types: FX, futures, stocks, commodities, metals, crypto</span></div></div>
<p><b>How it began.</b> Activity in these markets began with a personal account in 2020. The current, continuous phase started in September 2023 and has run for 36 months, or three full years, through ${ASOF}.</p>
<p><b>How it broadened.</b> From 2023, activity widened beyond currencies (foreign exchange, or FX) to oil and gold, then in 2024 to silver, US index futures, Bitcoin and Nigerian equities, and in 2025 to US equities. Three paths have been used: personal accounts; accounts with proprietary trading firms (“prop firms”), each beginning as a paid evaluation of trading ability; and the US Equity Account, a longer-horizon US stock account. Together that is ${D.ACCOUNTS.filter(a=>a.id!=='ALPARI-2020').length} accounts and ${f(nTr)} trades.</p>
<p><b>Prop firms.</b> ${prop.length} prop-firm accounts were run, paying ${usd(fees)} in fees. They provided ${usd(capSz)} of account capacity and produced an account-level result of ${pcs(evPnl/capSz)}. Two stages were passed; no payouts have been received.</p>
<p><b>The equity accounts.</b> Both are active. The US Equity Account, trading on the NYSE and Nasdaq, earned ${sg(kh.pnl)} on ${usd(1000)} (${pc(kh.pnl/1000)}). The Nigerian Equity Account, traded on the Nigerian Exchange (NGX), earned <span class="pos">+${ngn(ngxN)}</span> net of fees on ${ngn(ngxCap)} of capital at its peak (${pc(ngxN/ngxCap)}).</p>
<p><b>Current position.</b> By ${ASOF} the net result across the current phase stood at ${usd(overall)}. 2025 and 2026 each finished the year net positive, led by the two equity accounts.</p>
<div class="note">Figures reflect money that actually moved: prop-firm fees paid, and results from closed trades in personal accounts and the two equity accounts. Evaluation-account profit and loss, which stayed inside the evaluation and was never received, is reported separately as a memo item.</div>`,SRCTXT));
P.push(page('1 · Timeline',`The current phase has run continuously since September 2023`,`<div class="lg"><span><i style="background:#2251FF"></i>Spot FX and price-tracking contracts (CFDs)</span><span><i style="background:#051C2C"></i>US futures</span><span><i style="background:#00A9F4"></i>US equities</span><span><i style="background:#12805C"></i>Nigerian equities</span></div>${gantt()}
<p style="margin-top:4mm">The current phase began in September 2023 with a personal account and nine prop-firm accounts in FX and index futures through 2024. The Nigerian Equity Account started in 2024 and the US Equity Account in 2025, and six further prop-firm accounts ran in 2026. Both equity accounts remain active. Numbered markers on the next page refer to events over this period.</p>`,SRCTXT));
P.push(page('1 · Timeline',`Each phase of activity overlapped a major macro or geopolitical shock`,T(['#','Period','Event','Relevance to the markets traded'],EV.map((e,i)=>{const d=x=>new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});return[i+1,e[1]?`${d(e[0])} – ${d(e[1])}`:d(e[0]),e[2],e[3]]}))+`<p style="font-size:8pt;color:#5B6B7A">Dates for 2026 events are from public reporting as of ${ASOF}; the Hormuz crisis is ongoing.</p>`,SRCTXT));
const mk=rows.map(r=>[r.k,r.rg,r.acc?'Prop-firm &amp; personal':'Equity account',f(r.n),pc(r.n/nTr),sg(r.acc+r.fund)]);
P.push(page('2 · Markets',`Where the ${usd(cap)} deployed in the current phase has gone, by market`,
`<h3>Where the capital went, by market</h3>${pie()}
<h3>By market type</h3>${T(['Market type','Region','Path','Trades','Share of trades','Result'],[...mk,{t:['Total','','',f(nTr),'100%',sg(sum(rows.map(r=>r.acc+r.fund)))]}])}
<p>US covers futures, equity indices (CFDs) and the US Equity Account. Global covers FX, commodities, metals and crypto, all traded through contracts for difference (CFDs), which track a price without owning the asset. Crypto is four BTCUSD trades in one 2024 evaluation. Prop-firm and personal-account results are account-level, including evaluation accounts; equity-account results are realised gains, with the Nigerian Equity Account converted to USD at prevailing monthly rates.</p>`,SRCTXT));
const pf=['MyFundedFutures','MyFundedFX','FundedNext','The5ers'].map(n=>{const s=prop.filter(a=>a.platform===n);return{n:FN[n],c:s.length,fee:sum(s.map(a=>a.costOfFund)),sz:sum(s.map(a=>a.size)),each:(()=>{const z=s.map(a=>a.size),lo=Math.min(...z),hi=Math.max(...z);return lo===hi?usd(lo):usd(lo)+'–'+usd(hi)})(),ev:sum(s.map(a=>a.pnl)),ok:s.filter(a=>a.pnl>0).length}});
P.push(page('3 · Entry paths',`Prop evaluations: ${prop.length} attempts, ${usd(fees)} in fees, ${usd(capSz)} of account capacity`,
`<p>${prop.length} prop-firm accounts across four firms provided ${usd(capSz)} of account capacity, for ${usd(fees)} in fees (${f(fees/capSz*100,2)}% of capacity). The aggregate account-level result was ${pcs(evPnl/capSz)}. Two stages were passed; no payouts have been received.</p>`+T(['Entry path','Accounts','Capital deployed','Result','Status'],[['Retail investing (personal accounts)',`2: Personal FX account, Nigerian Equity Account`,usd(sum(pers.map(a=>a.size))+ngxCapUSD),sg(persPnl+ngxU),'Active'],['Prop firms',`${prop.length}: four firms`,usd(fees),sg(-fees),'All closed; 0 payouts'],['US Equity Account','1: a longer-horizon equity account',usd(1000),sg(kh.pnl),'Active'],{t:['Total',String(D.ACCOUNTS.filter(a=>a.id!=='ALPARI-2020').length),usd(cap),sg(overall),'']}])+
`<h3>Prop firms: totals by firm</h3>${T(['Firm','Accounts','Size per account','Total account size','Total fees paid','Total account-level result','% of total size','Stages passed'],[...pf.map(p=>[p.n,p.c,p.each,usd(p.sz),usd(p.fee,2),sg(p.ev),pcs(p.ev/p.sz),p.ok]),{t:['All four firms',prop.length,'',usd(capSz),usd(fees,2),sg(evPnl),pcs(evPnl/capSz),passed]}])}
<p style="font-size:8pt;color:#5B6B7A">Totals are summed across each firm’s accounts, and each account is counted at its full size, including later stages of the same evaluation.</p><h3>Evaluation fees by firm</h3>${dbar(pf.map(p=>({l:p.n,v:p.fee,c:'#051C2C'})),{lw:130})}
<p style="margin-top:3mm">Three of the five ${FN.MyFundedFutures} evaluations ended at about −4% ($2,000 each), consistent with a fixed maximum-loss rule set by the firm. Retail accounts are self-directed personal accounts. The other path is the US Equity Account, a longer-horizon account traded since February 2025. Both stages passed were at ${FN.The5ers} in May 2026.</p>`,SRCTXT));
const z=v=>Math.abs(v)<0.5?'':sg(v),yt=yrs.map(y=>[y,z(Y[y].p),z(-Y[y].fee),z(Y[y].kh),z(Y[y].ng),sg(net(y)),sp(net(y)/inPlay(y))]);
P.push(page('4 · Performance',`Year-end results turned positive in 2025 and 2026, after a low in 2024`,
`<h3>By year (USD)</h3>${T(['Year','Personal accounts','Prop fees','US Equity Account','Nigerian Equity Account','Net result','Net result %'],[...yt,{t:['Total',sg(persPnl),sg(-fees),sg(kh.pnl),sg(ngxU),sg(overall),sp(overall/cap)]}])}<p style="font-size:8pt;color:#5B6B7A">Net result % compares each year’s result with the capital in active accounts that year, not with the full ${usd(cap)} deployed over the whole period. The chart below tracks the same idea continuously.</p>
<div class="lg"><span><i style="background:#051C2C"></i>Personal accounts</span><span><i style="background:#2251FF"></i>Prop-firm evaluations</span><span><i style="background:#12805C"></i>Equity accounts</span></div>
<h3>Cumulative result as a share of capital committed (36 months to date)</h3>${journeyChart()}
<p style="font-size:8pt;color:#5B6B7A">Each month’s figure is the running result divided by the running capital committed since September 2023. For prop-firm accounts, capital committed is the fee paid; for personal accounts and the two equity accounts, it is the capital placed in the account.</p>`,SRCTXT));
P.push(page('4 · Performance',`Prop-firm evaluations dominate the result; the two equity accounts are the exception`,
`<h3>By path, result against its own base</h3>${T(['Path','Base','Base amount','Result','Result %'],[['Personal FX account','Capital deployed',usd(sum(pers.map(a=>a.size))),sg(persPnl),sp(persPnl/sum(pers.map(a=>a.size)))],['Nigerian Equity Account','Peak capital committed',ngn(ngxCap),`<span class="pos">+${ngn(ngxN)}</span>`,sp(ngxN/ngxCap)],['US Equity Account','Capital contributed',usd(1000),sg(kh.pnl),sp(kh.pnl/1000)],['Prop-firm fees','Account size',usd(capSz),sg(-fees),`<span class="neg">−${f(fees/capSz*100,2)}%</span>`],['Prop-firm accounts, account level','Account size',usd(capSz),sg(evPnl),sp(evPnl/capSz)]])}
<p style="font-size:8pt;color:#5B6B7A">The Nigerian Equity Account is shown in naira; every other row is in USD.</p>
<h3>By market type, account-level result including evaluation accounts</h3>${dbar(rows.map(r=>({l:r.k,l2:`· ${pc(r.n/nTr)} of trades`,v:r.acc+r.fund})),{lw:185,rh:19})}
<p style="margin-top:3mm"><b>Status:</b> ${D.ACCOUNTS.filter(a=>a.status==='completed'&&a.id!=='ALPARI-2020').length} accounts closed, 2 active. Nigerian Equity Account in naira: ${ngn(ngxG)} gross, ${ngn(ngxF)} fees, ${ngn(ngxN)} net across ${ngx.length} closed trades.</p>`,SRCTXT));
P.push(page('5 · Equity accounts',`Both equity accounts are active: the US Equity Account is up ${pc(kh.pnl/1000)} and the Nigerian Equity Account ${pc(ngxN/ngxCap)} on capital committed at its peak`,
`<p>Results are realised gains only, meaning positions that have been sold. Nigerian Equity Account results are after fees.</p>
${T(['Account','Started','Peak capital','Realised result','Return','Closed trades'],[['US Equity Account','Feb 2025',usd(1000),sg(kh.pnl),sp(kh.pnl/1000),f(D.KHOOD_TRADES.length)],['Nigerian Equity Account','May 2024',ngn(ngxCap),`<span class="pos">+${ngn(ngxN)}</span>`,sp(ngxN/ngxCap),f(ngx.length)]])}
<h3>Cumulative return on capital contributed (%)</h3><div class="lg"><span><i style="background:#00A9F4"></i>US Equity Account</span><span><i style="background:#12805C"></i>Nigerian Equity Account</span></div>
${area({ss:[{pts:ngS,c:'#12805C'},{pts:khS,c:'#00A9F4'}],x0:mi('2024-05-01'),x1:80,y0:0,y1:80,st:20,fmt:v=>v+'%',H:210,marks:[{m:80,v:khS.at(-1)[1],t:`US Equity Account ${pcs(khS.at(-1)[1]/100)}`,a:'end',dx:-8,dy:-9,c:'#00A9F4'},{m:80,v:ngS.at(-1)[1],t:`Nigerian Equity Account ${pcs(ngS.at(-1)[1]/100)}`,a:'end',dx:-8,dy:17,c:'#12805C'}]})}
<h3>US Equity Account: cumulative trading result (USD)</h3><div class="lg"><span><i style="background:#00A9F4"></i>Trading result</span></div>
${area({ss:[{pts:khU,c:'#00A9F4'}],x0:mi('2025-02-01'),x1:80,y0:0,y1:1600,st:400,H:180,marks:[{m:80,v:khU.at(-1)[1],t:`Trading result ${usd(khU.at(-1)[1])}`,a:'end',dx:-8,dy:-9,c:'#00A9F4'}]})}
<p style="margin-top:2mm">Payouts from the US Equity Account to date exceed its cumulative trading result, so part of the original capital placed in the account has also been returned.</p>`,SRCTXT));
P.push(page('6 · Research approach',`The approach is pattern recognition, and trading has become more selective: ${avg('2024')} trades per account in 2024, ${avg('2026')} in 2026`,
`<p><b>Primary approach.</b> Generating value from the markets through the application of the art, science and technology of pattern recognition.</p>
<div class="cols"><div><h3>Art</h3><p>Recognising patterns on the chart as they form, and reading what they suggest in the moment.</p></div><div><h3>Science</h3><p>Testing whether a pattern repeats with an edge: samples, expectancy and risk limits rather than anecdote.</p></div><div><h3>Technology</h3><p>Encoding what works into indicators, dashboards and automated systems so it can be applied without drift.</p></div></div>
<h3>Supporting lenses</h3>${T(['Lens','Role'],[['Technical analysis','Structure, levels, momentum and reversal signals across FX, futures and stocks'],['Fundamentals','Sector and company selection for the equity accounts, including thematic sector intelligence'],['Events','Macro and geopolitical catalysts: rates, elections, wars, supply shocks (see events, page 3)']])}
<h3>How trading has changed since 2024</h3>${T(['Prop-firm accounts opened in','2024','2026'],[['Number of accounts',c24.n,c26.n],['Average trades per account',avg('2024'),avg('2026')],['Most trades in one account',Math.max(...prop.filter(a=>a.startDate<'2025').map(a=>a.trades)),Math.max(...prop.filter(a=>a.startDate>'2025').map(a=>a.trades))],['Result against account size',sp(c24.pl/c24.sz),sp(c26.pl/c26.sz)],['Accounts finishing positive',`${c24.up} of ${c24.n}`,`${c26.up} of ${c26.n}`]])}<p>In plain terms: fewer trades per account, smaller losses against account size, and the first accounts to finish ahead. There were only 15 accounts, with different firms and account sizes each year. Averages use the accounts that have trade records.</p>
<h3>Tooling built along the way</h3><p>Rule-based systems and dashboards are part of the approach: automated trading rules for two trading platforms, an intraday trading engine, charting indicators, and sector-intelligence tools.</p>`,SRCTXT));
P.push(page('Notes',`Basis of preparation`,
`<p><b>Basis of the figures.</b> Personal accounts show the account’s realised result; prop firms show the evaluation fee paid, not the evaluation account’s own profit or loss; equity accounts show trading result net of any payouts. Evaluation-account profit and loss is reported separately, as a memo item.</p>
<p><b>Currency.</b> Reported in USD. Nigerian Equity Account results are recorded in naira and converted to USD at approximate monthly ₦/$ levels: recorded rates for 2024 and published Central Bank of Nigeria levels for 2025–26 (about ₦1,360–1,530).</p>
<p><b>Nigerian Equity Account.</b> Gains are shown net of fees: ${ngn(ngxG)} gross, less ${ngn(ngxF)} in fees, for ${ngn(ngxN)} net. One open position (6 shares of Geregu Power, bought for ₦5,400) has not been sold and is excluded from the results; it was running ₦446 below cost. This account has no separate deposit log, so its capital is estimated from the trade record itself: the largest amount ever tied up at one time, tracking each purchase and sale in order. That peak, ${ngn(ngxCap)}, was reached in March 2026 and is used as the capital base for its return.</p>
<p><b>Scope.</b> This overview covers the current, continuous phase of activity: September 2023 to date. An earlier personal account traded briefly in 2020; its figures are not included in the totals, tables or charts above.</p>
<p><b>Data gaps.</b> A few accounts rely on account-level summaries rather than complete trade-by-trade records. These differences are minor and do not change the overall picture.</p>
<p><b>Other notes.</b> No prop payouts and no other accounts beyond those shown here.</p>
<p><b>Sources.</b> Account and trade-level portfolio records, and Nigerian Equity Account trade records. Event dates are from public reporting. Data as of ${ASOF}.</p>
<p><b>Terms.</b> A prop firm is a proprietary trading firm that lets a trader use its account after passing a paid evaluation. FX is trading one currency against another; futures are standardised contracts on an index or commodity. A CFD is a contract for difference, which tracks a price without owning the asset. NGX is the Nigerian Exchange, where Nigerian equities are traded.</p>`,SRCTXT));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Financial market participation, 2023–2026 · ${NAME}</title><link rel="stylesheet" href="assets/report.css"><script>
var REPORT={name:"${NAME}",date:"${DATE}"};
</script></head><body><div class="bar"><span>Financial market participation, 2023–2026</span><a href="${PDF}" download data-pdf-name="${NAME}">Download PDF</a></div>${P.join('\n')}<script>(function(){var q=function(s){return document.querySelectorAll(s)};
q('[data-name]').forEach(function(e){e.textContent=REPORT.name});q('[data-date]').forEach(function(e){e.textContent=REPORT.date});
document.title='Financial market participation, 2023–2026 · '+REPORT.name;
var a=q('.bar a')[0];if(REPORT.name!==a.getAttribute('data-pdf-name')){a.addEventListener('click',function(ev){ev.preventDefault();window.print()})}
document.documentElement.style.setProperty('--z',Math.min(1,innerWidth/800))})()</script></body></html>`;
fs.writeFileSync(R+'/overview.html',html);
console.log(JSON.stringify({cap:+cap.toFixed(2),overall:+overall.toFixed(2),nTr,ngxU:+ngxU.toFixed(2),ngxN,fees,persPnl,evPnl,passed,MT}));
