// node tools/build.mjs  ->  index.html  (then: node tools/make-pdf.cjs)
import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const D=new Function(fs.readFileSync(R+'/tools/data.js','utf8').replace("'use strict';",'')+';return {ACCOUNTS,TRADE_DATA,KHOOD_TRADES,NGX_TRADES,KHOOD_WITHDRAWALS}')();
const VER='1.2.0',ASOF='September 2026',NAME='Foabao',DATE='September 2026',PDF='Foabao-Financial-Market-Participation-2020-2026.pdf';
const sum=a=>a.reduce((s,x)=>s+x,0),f=(n,d=0)=>n.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const usd=(n,d=0)=>(n<0?'−':'')+'$'+f(Math.abs(n),d),sg=(n,d=0)=>`<span class="${n<0?'neg':'pos'}">${n<0?'−':'+'}$${f(Math.abs(n),d)}</span>`,ngn=n=>(n<0?'−':'')+'₦'+f(Math.abs(n)),pc=n=>f(n*100)+'%';
// ₦/$ anchors: user-recorded rates (2024), CBN NFEM levels otherwise; linear between anchors
const FX=[['2024-05-29',1393],['2024-07-05',1530],['2025-02-27',1530],['2025-07-15',1530],['2025-08-28',1510],['2025-10-24',1455],['2026-01-09',1445],['2026-03-25',1380],['2026-05-15',1362],['2026-09-18',1364]];
const rate=d=>{const t=+new Date(d);for(let i=1;i<FX.length;i++){const a=+new Date(FX[i-1][0]),b=+new Date(FX[i][0]);if(t<=b)return t<=a?FX[i-1][1]:FX[i-1][1]+(FX[i][1]-FX[i-1][1])*(t-a)/(b-a)}return FX.at(-1)[1]};
const cls=i=>{i=(i||'').split(',')[0].trim().toUpperCase();if(/^(M?NQ|M?ES|M?YM)[FGHJKMNQUVXZ]\d$/.test(i))return'Futures';if(/WTI|XTI|CRUDE/.test(i))return'Commodities';if(/^(XA|A)[UG][A-Z]{3}$/.test(i))return'Metals';if(/BTC|ETH/.test(i))return'Crypto';if(/^(SPX|SP500|NAS100)/.test(i))return'Equities';if(/^[A-Z]{6}$/.test(i))return'FX';return null};
// ── data
const A=D.ACCOUNTS.filter(a=>a.id!=='NGX'),prop=A.filter(a=>a.type.startsWith('prop')),pers=A.filter(a=>a.type==='personal'),kh=A.find(a=>a.id==='1KHOOD');
const ngx=D.NGX_TRADES.filter(t=>!t.open).map(t=>({...t,net:t.netPnl-t.fees,usd:(t.netPnl-t.fees)/rate(t.closeDate)}));
const ngxG=sum(ngx.map(t=>t.netPnl)),ngxF=sum(ngx.map(t=>t.fees)),ngxN=ngxG-ngxF,ngxU=sum(ngx.map(t=>t.usd));
const fees=sum(prop.map(a=>a.costOfFund)),persPnl=sum(pers.map(a=>a.pnl)),evPnl=sum(prop.map(a=>a.pnl)),passed=prop.filter(a=>a.pnl>0).length;
const overall=persPnl-fees+kh.pnl+ngxU;
const rows=[['Futures','US'],['Equity indices (CFDs)','US'],['US stocks','US'],['Nigerian stocks','Nigeria'],['FX','Global'],['Commodities','Global'],['Metals','Global'],['Crypto','Global']].map(([k,rg])=>({k,rg,n:0,acc:0,fund:0}));
const row=k=>rows.find(x=>x.k===k),mp={Futures:'Futures',Equities:'Equity indices (CFDs)',FX:'FX',Commodities:'Commodities',Metals:'Metals',Crypto:'Crypto'};
for(const a of A){if(a.id==='1KHOOD')continue;const def=a.id.startsWith('MFFU')?'Futures':'FX';let s=0;for(const t of D.TRADE_DATA[a.id]||[]){const p=t.netPnl||0,sm=/SUMMARY|REMAIN/i.test(t.instrument||''),x=row(mp[(!sm&&cls(t.instrument))||def]);if(!sm)x.n++;x.acc+=p;s+=p}row(mp[def]).acc+=a.pnl-s}
row('US stocks').n=D.KHOOD_TRADES.length;row('US stocks').fund=kh.pnl;row('Nigerian stocks').n=ngx.length;row('Nigerian stocks').fund=ngxU;
const nTr=sum(rows.map(r=>r.n));
const yrs=[2020,2023,2024,2025,2026],Y=Object.fromEntries(yrs.map(y=>[y,{p:0,fee:0,kh:0,ng:0,ev:0}]));
for(const a of pers)Y[a.endDate.slice(0,4)].p+=a.pnl;for(const a of prop){Y[a.startDate.slice(0,4)].fee+=a.costOfFund;Y[a.endDate.slice(0,4)].ev+=a.pnl}
for(const t of D.KHOOD_TRADES)Y[t.closeDate.slice(0,4)].kh+=t.netPnl;for(const t of ngx)Y[t.closeDate.slice(0,4)].ng+=t.usd;
const net=y=>Y[y].p-Y[y].fee+Y[y].kh+Y[y].ng;
const capSz=sum(prop.map(a=>a.size)),pcs=x=>(x<0?'−':'+')+f(Math.abs(x)*100,1)+'%',coh=t=>{const q=prop.filter(a=>t(a.startDate));return{n:q.length,sz:sum(q.map(a=>a.size)),pl:sum(q.map(a=>a.pnl)),up:q.filter(a=>a.pnl>0).length}},c24=coh(d=>d<'2025'),c26=coh(d=>d>'2025'),cum=[];{let c=0;for(const y of yrs){c+=net(y);cum.push(c)}}
const capOf=a=>a.id==='NGX'?107.64:a.type.startsWith('prop')?a.costOfFund:a.size,inPlay=y=>sum(D.ACCOUNTS.filter(a=>+a.startDate.slice(0,4)<=y&&(a.endDate?+a.endDate.slice(0,4):2026)>=y).map(capOf)),sp=x=>`<span class="${x<0?'neg':'pos'}">${pcs(x)}</span>`;
const mi=s=>(+s.slice(0,4)-2020)*12+(+s.slice(5,7)-1),MON=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],mn=i=>MON[i%12]+' '+(2020+Math.floor(i/12)),N=mi('2026-09-30')+1;
const cumM=(ev,from=0)=>{const d=new Array(N).fill(0);ev.forEach(([m,v])=>{d[m]+=v});let c=0;const o=[];d.forEach((x,i)=>{c+=x;if(i>=from)o.push([i,c])});return o};
const cashS=cumM([...pers.map(a=>[mi(a.endDate),a.pnl]),...prop.map(a=>[mi(a.startDate),-a.costOfFund]),...D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl]),...ngx.map(t=>[mi(t.closeDate),t.usd])]),cMin=cashS.reduce((a,b)=>b[1]<a[1]?b:a);
const routeOf=a=>a.type==='personal'?'Personal':a.type.startsWith('prop')?'Prop':'Fund',RC={Personal:'#051C2C',Prop:'#2251FF',Fund:'#12805C'};
const capCumM=cumM(D.ACCOUNTS.map(a=>[mi(a.startDate),capOf(a)])),roiS=[];for(let i=0;i<N;i++)if(capCumM[i][1]>0)roiS.push([i,cashS[i][1]/capCumM[i][1]*100]);
const ngS=cumM(ngx.map(t=>[mi(t.closeDate),(t.netPnl-t.fees)/1500]),mi('2024-05-01')),khS=cumM(D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl/10]),mi('2025-02-01')),khU=cumM(D.KHOOD_TRADES.map(t=>[mi(t.closeDate),t.netPnl]),mi('2025-02-01')),khD=cumM(D.KHOOD_WITHDRAWALS.map(w=>[mi(w.date),w.amountUSD]),mi('2025-02-01'));
// funding: [destination, region, path, {source:USD}]  (unstated sources default to IF)
const F=[['Alpari 2020','Global','Retail',{IF:131.58,PO:163.13}],['Alpari 2023','Global','Retail',{IF:75.35,MO:195.64,TA:156.27}],['MyFundedFX evaluations (4)','Global','Prop',{TA:84,IF:64.22}],['MyFundedFutures evaluations (5)','US','Prop',{MO:165,BA:295,IF:274.5}],['FundedNext and The5ers evaluations (6)','Global','Prop',{IF:133.71}],['1kHooD fund','US','Managed',{TA:1000}],['Nigerian stocks (brokerage account)','Nigeria','Retail',{BA:107.64}]];
const SRC=['IF','PO','TA','MO','BA'],GRP={IF:'Personal',PO:'Friend',TA:'Friend',MO:'Family',BA:'Family'},SC={IF:'#051C2C',TA:'#2251FF',PO:'#00A9F4',MO:'#12805C',BA:'#7CC8A9'};
const fs_=Object.fromEntries(SRC.map(s=>[s,sum(F.map(r=>r[3][s]||0))])),cap=sum(Object.values(fs_)),grp=g=>sum(SRC.filter(s=>GRP[s]===g).map(s=>fs_[s]));
const reg=g=>sum(F.filter(r=>r[1]===g).map(r=>sum(Object.values(r[3]))));
const wd=D.KHOOD_WITHDRAWALS,wU=sum(wd.map(w=>w.amountUSD)),gpG=sum(wd.map(w=>w.gpGBP)),lpG=sum(wd.map(w=>w.lpGBP)),lpU=wU*lpG/(gpG+lpG),gpU=wU-lpU,implied=1000+kh.pnl-wU;
const MT={};for(const r of F){const k=r[0].startsWith('MyFundedFutures')?'US futures':r[0].startsWith('1kHooD')?'US stocks':r[1]==='Nigeria'?'Nigerian stocks':'Global FX and CFDs';MT[k]=(MT[k]||0)+sum(Object.values(r[3]))}
const MC={'Global FX and CFDs':['#2251FF','Global'],'US stocks':['#00A9F4','US'],'US futures':['#051C2C','US'],'Nigerian stocks':['#12805C','Nigeria']};
const avg=y=>{const s=prop.filter(a=>a.startDate.startsWith(y)&&a.trades>0);return Math.round(sum(s.map(a=>a.trades))/s.length)};
// ── charts
const svg=(w,h,b)=>`<svg viewBox="0 0 ${w} ${h}" role="img">${b}</svg>`;
const dbar=(rs,{w=690,lw=185,fmt=usd,rh=22}={})=>{const pad=66,v=rs.map(r=>r.v),mn=Math.min(0,...v),mx=Math.max(0,...v),sc=(w-lw-pad*2)/((mx-mn)||1),z=lw+pad-mn*sc;
 return svg(w,rs.length*rh+6,`<line x1="${z}" x2="${z}" y1="0" y2="${rs.length*rh+3}" stroke="#8A97A5"/>`+rs.map((r,i)=>{const y=i*rh+3,bw=Math.abs(r.v)*sc,x=r.v<0?z-bw:z;return`<text x="0" y="${y+13}" class="l">${r.l}</text><rect x="${x}" y="${y+2}" width="${Math.max(bw,1)}" height="${rh-9}" fill="${r.c||(r.v<0?'#B3261E':'#2251FF')}"/><text x="${r.v<0?x-4:x+bw+4}" y="${y+13}" text-anchor="${r.v<0?'end':'start'}" class="v">${fmt(r.v)}</text>`}).join(''))};
const mono=P=>{const n=P.length,d=[],m=[];for(let i=0;i<n-1;i++)d[i]=(P[i+1][1]-P[i][1])/(P[i+1][0]-P[i][0]);m[0]=d[0];m[n-1]=d[n-2];for(let i=1;i<n-1;i++)m[i]=d[i-1]*d[i]<=0?0:(d[i-1]+d[i])/2;
 for(let i=0;i<n-1;i++){if(d[i]===0){m[i]=m[i+1]=0}else{const a=m[i]/d[i],b=m[i+1]/d[i],h=Math.hypot(a,b);if(h>3){const t=3/h;m[i]=t*a*d[i];m[i+1]=t*b*d[i]}}}
 let s=`M${P[0][0]},${P[0][1]}`;for(let i=0;i<n-1;i++){const dx=(P[i+1][0]-P[i][0])/3;s+=`C${P[i][0]+dx},${P[i][1]+m[i]*dx} ${P[i+1][0]-dx},${P[i+1][1]-m[i+1]*dx} ${P[i+1][0]},${P[i+1][1]}`}return s};
let gi=0;
const area=({ss,x0,x1,y0,y1,st,fmt=usd,H=200,bands=[],marks=[]})=>{const W=690,L=54,R=18,T=14,B=26,id='g'+(gi++),X=m=>L+(m-x0)/(x1-x0)*(W-L-R),Y=v=>T+(y1-v)/(y1-y0)*(H-T-B),zb=Y(Math.min(Math.max(0,y0),y1)),PT=q=>q.pts.map(([m,v])=>[X(m),Y(v)]);
 let s='<defs>'+ss.map((q,k)=>`<linearGradient id="${id}${k}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${q.c}" stop-opacity="${q.neg?0.04:0.34}"/><stop offset="1" stop-color="${q.c}" stop-opacity="${q.neg?0.34:0.04}"/></linearGradient>`).join('')+'</defs>';
 bands.forEach(b=>{s+=`<rect x="${X(b[0])}" y="${T}" width="${X(b[1])-X(b[0])}" height="${H-T-B}" fill="#F0F3F7"/><text x="${(X(b[0])+X(b[1]))/2}" y="${T+11}" text-anchor="middle" class="l m">${b[2]}</text>`});
 for(let v=Math.ceil(y0/st)*st;v<=y1+1e-9;v+=st)s+=`<line x1="${L}" x2="${W-R}" y1="${Y(v)}" y2="${Y(v)}" stroke="${v===0?'#8A97A5':'#E3E9EF'}"/><text x="${L-6}" y="${Y(v)+3}" text-anchor="end" class="l m">${fmt(v)}</text>`;
 for(let y=2020;y<=2027;y++){const m=(y-2020)*12;if(m>=x0-0.5&&m<x1)s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${T}" y2="${H-B}" stroke="#E3E9EF" stroke-dasharray="2 3"/><text x="${X(m)+3}" y="${H-9}" class="l m">${y}</text>`}
 ss.forEach((q,k)=>{const P=PT(q);s+=`<path d="${mono(P)}L${P.at(-1)[0]},${zb}L${P[0][0]},${zb}Z" fill="url(#${id}${k})"/>`});
 ss.forEach(q=>{s+=`<path d="${mono(PT(q))}" fill="none" stroke="${q.c}" stroke-width="2" stroke-linejoin="round"/>`});
 marks.forEach(k=>{s+=`<circle cx="${X(k.m)}" cy="${Y(k.v)}" r="3.6" fill="${k.c||'#051C2C'}" stroke="#fff" stroke-width="1.5"/><text x="${X(k.m)+(k.dx||0)}" y="${Y(k.v)+(k.dy||0)}" text-anchor="${k.a||'middle'}" class="v">${k.t}</text>`});
 return svg(W,H,s)};
const journeyChart=()=>{const W=690,L=54,R=18,T=16,B=52,H=250,plotH=H-T-B,x0=roiS[0][0],x1=80,y0=-105,y1=10,st=25,X=m=>L+(m-x0)/(x1-x0)*(W-L-R),Y=v=>T+(y1-v)/(y1-y0)*plotH;
 let s='<defs><linearGradient id="jg" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#2251FF" stop-opacity="0.05"/><stop offset="1" stop-color="#2251FF" stop-opacity="0.32"/></linearGradient></defs>';
 s+=`<rect x="${X(5.2)}" y="${T}" width="${X(44.3)-X(5.2)}" height="${plotH}" fill="#F0F3F7"/><text x="${(X(5.2)+X(44.3))/2}" y="${T+11}" text-anchor="middle" class="l m">Pause between streaks</text>`;
 for(let v=Math.ceil(y0/st)*st;v<=y1+1e-9;v+=st)s+=`<line x1="${L}" x2="${W-R}" y1="${Y(v)}" y2="${Y(v)}" stroke="${v===0?'#8A97A5':'#E3E9EF'}"/><text x="${L-6}" y="${Y(v)+3}" text-anchor="end" class="l m">${v}%</text>`;
 for(let y=2020;y<=2027;y++){const m=(y-2020)*12;if(m>=x0-0.5&&m<=x1)s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${T}" y2="${T+plotH}" stroke="#E3E9EF" stroke-dasharray="2 3"/><text x="${X(m)+3}" y="${T+plotH+11}" class="l m">${y}</text>`}
 const P=roiS.map(([m,v])=>[X(m),Y(v)]),zY=Y(0);
 s+=`<path d="${mono(P)}L${P.at(-1)[0]},${zY}L${P[0][0]},${zY}Z" fill="url(#jg)"/><path d="${mono(P)}" fill="none" stroke="#2251FF" stroke-width="2" stroke-linejoin="round"/>`;
 const tb=T+plotH+24;
 D.ACCOUNTS.forEach(a=>{const m=mi(a.startDate);if(m<x0-0.5||m>x1)return;const h=Math.max(2,Math.sqrt(capOf(a))*0.7);s+=`<line x1="${X(m)}" x2="${X(m)}" y1="${tb}" y2="${tb-h}" stroke="${RC[routeOf(a)]}" stroke-width="2"/>`});
 s+=`<line x1="${L}" x2="${W-R}" y1="${tb}" y2="${tb}" stroke="#D5DCE4"/><text x="${L}" y="${tb+12}" class="l m">Each mark is one account at its start date; taller marks committed more capital</text>`;
 const last=roiS.at(-1);s+=`<circle cx="${X(80)}" cy="${Y(last[1])}" r="3.6" fill="#051C2C" stroke="#fff" stroke-width="1.5"/><text x="${X(80)-8}" y="${Y(last[1])-9}" text-anchor="end" class="v">${pcs(last[1]/100)}, Sep 2026</text>`;
 return svg(W,H,s)};
const pie=()=>{const ps=Object.entries(MT).sort((a,b)=>b[1]-a[1]).map(([k,v])=>({k,v,c:MC[k][0],rg:MC[k][1]})),t=sum(ps.map(p=>p.v)),cx=105,cy=100,R=90,r=56,P=(d,g)=>[cx+d*Math.cos(g),cy+d*Math.sin(g)];let a=-Math.PI/2,s='';
 ps.forEach((p,i)=>{const b=a+p.v/t*2*Math.PI,[x1,y1]=P(R,a),[x2,y2]=P(R,b),[x3,y3]=P(r,b),[x4,y4]=P(r,a),lg=b-a>Math.PI?1:0;
  s+=`<path d="M${x1},${y1}A${R},${R} 0 ${lg} 1 ${x2},${y2}L${x3},${y3}A${r},${r} 0 ${lg} 0 ${x4},${y4}Z" fill="${p.c}" stroke="#fff" stroke-width="2"/>`;
  if(p.v/t>.1){const m=(a+b)/2,[tx,ty]=P((R+r)/2,m);s+=`<text x="${tx}" y="${ty+3}" text-anchor="middle" class="v w">${pc(p.v/t)}</text>`}
  const y=44+i*38;s+=`<rect x="262" y="${y-9}" width="10" height="10" fill="${p.c}"/><text x="280" y="${y}" class="v">${p.k}</text><text x="280" y="${y+13}" class="l m">${p.rg} · ${usd(p.v)}</text><text x="650" y="${y+6}" text-anchor="end" style="font:600 17px 'Source Serif 4',Georgia,serif;fill:#051C2C">${pc(p.v/t)}</text>`;a=b});
 s+=`<text x="${cx}" y="${cy-2}" text-anchor="middle" style="font:600 17px 'Source Serif 4',Georgia,serif;fill:#051C2C">${usd(t)}</text><text x="${cx}" y="${cy+13}" text-anchor="middle" class="l m">deployed</text>`;return svg(690,200,s)};
const stack=(ps,w=690)=>{let x=0;const t=sum(ps.map(p=>p.v));return svg(w,62,ps.map(p=>{const bw=p.v/t*w,o=`<rect x="${x}" y="0" width="${bw-1}" height="28" fill="${p.c}"/><text x="${x+5}" y="18" class="v w">${p.l}</text><text x="${x+2}" y="42" class="l">${pc(p.v/t)}</text><text x="${x+2}" y="54" class="l m">${usd(p.v)}</text>`;x+=bw;return o}).join(''))};
const EV=[['2020-03-11','2020-06-01','COVID-19 pandemic and market crash','Record volatility; first live account (Alpari 2020) traded through it'],['2020-11-03',0,'US presidential election','Rotation and volatility in US equities and the dollar'],['2022-02-24',0,'Russia–Ukraine war begins','Energy and grain shock; commodity and inflation repricing (no participation, 2021–22)'],['2022-11-30',0,'ChatGPT released','Start of the AI investment cycle behind later US equity leadership'],['2023-03-10',0,'Silicon Valley Bank collapse','Regional-bank stress; rates repriced'],['2023-05-29','2023-06-14','Nigeria: subsidy removal and FX unification','Naira devalued; reshaped the cost of dollar capital'],['2023-10-07',0,'Israel–Hamas war begins','Oil and gold volatility; Alpari 2023 traded WTI and gold'],['2024-01-01','2024-02-29','Naira sell-off','Peak dollar cost for Nigerian funders during the 2024 evaluations'],['2024-08-05',0,'Yen carry-trade unwind','Sharp fall across markets during the futures evaluations'],['2024-09-18',0,'Fed begins cutting rates','Start of the easing cycle'],['2024-11-05',0,'US presidential election','Trend day for US indices and the dollar'],['2025-04-02',0,'US “Liberation Day” tariffs','Global equity sell-off and rebound; 1kHooD first year'],['2025-06-13','2025-06-24','Israel–Iran 12-day war','Oil and gold spike'],['2026-02-28',0,'Iran war and Strait of Hormuz crisis (ongoing)','Oil spike toward $120 (Brent); US blockade of Iranian ports 13 Apr–29 May; Nigerian stock gains in 2026'],['2026-03-01',0,'','']].filter(e=>e[2]);
const col={spot:'#2251FF',futures:'#051C2C',stocks:'#00A9F4',ngx:'#12805C'};
const lab=a=>{if(a.id==='NGX')return'Nigerian stocks';if(a.id==='1KHOOD')return'1kHooD (US stocks)';if(a.type==='personal')return a.platform+' '+a.startDate.slice(0,4);const q=D.ACCOUNTS.filter(x=>x.platform===a.platform&&x.type.startsWith('prop')).sort((x,y)=>x.startDate<y.startDate?-1:1);return a.platform+' '+(q.indexOf(a)+1)};
const gantt=()=>{const W=690,L=124,T0=58,rh=15,x0=+new Date('2020-01-01'),x1=+new Date('2027-01-01'),X=d=>L+(+new Date(d)-x0)/(x1-x0)*(W-L-8),as=[...D.ACCOUNTS].sort((a,b)=>a.startDate<b.startDate?-1:1),H=T0+as.length*rh+22,B=as.length*rh;
 const g0='2020-06-02',g1='2023-09-11';let s=`<rect x="${X(g0)}" y="${T0-6}" width="${X(g1)-X(g0)}" height="${B+6}" fill="#F0F3F7"/><text x="${(X(g0)+X(g1))/2}" y="${T0+B/2}" text-anchor="middle" class="l m">Pause between streaks</text>`;
 for(let y=2020;y<=2027;y++)s+=`<line x1="${X(y+'-01-01')}" x2="${X(y+'-01-01')}" y1="${T0-6}" y2="${T0+B}" stroke="#D5DCE4"/>`+(y<2027?`<text x="${X(y+'-07-01')}" y="${H-6}" text-anchor="middle" class="l">${y}</text>`:'');
 EV.forEach((e,i)=>{const x=X(e[0]),y=12+(i%2)*17;s+=`<line x1="${x}" x2="${x}" y1="${y}" y2="${T0-6}" stroke="#9AA9B8" stroke-dasharray="2 2"/>`+(e[1]?`<rect x="${x}" y="${T0-9}" width="${Math.max(X(e[1])-x,2)}" height="3" fill="#00A9F4"/>`:'')+`<circle cx="${x}" cy="${y}" r="7" fill="#051C2C"/><text x="${x}" y="${y+3}" text-anchor="middle" class="v w" style="font-size:8px">${i+1}</text>`});
 as.forEach((a,i)=>{const y=T0+i*rh,x=X(a.startDate),w=Math.max(X(a.endDate||'2026-09-24')-x,3);s+=`<text x="${L-6}" y="${y+10}" text-anchor="end" class="l">${lab(a)}</text><rect x="${x}" y="${y+2}" width="${w}" height="9" rx="1" fill="${col[a.market]}"/>`+(a.endDate?'':`<text x="${x-4}" y="${y+10}" text-anchor="end" class="l m">active</text>`)});
 return svg(W,H,s)};
const T=(c,r,x='')=>`<table class="${x}"><thead><tr>${c.map((h,i)=>`<th${i?' class="r"':''}>${h}</th>`).join('')}</tr></thead><tbody>${r.map(q=>`<tr${q.t?' class="tot"':''}>${(q.t?q.t:q).map((h,i)=>`<td${i?' class="r"':''}>${h}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
let pg=0;const page=(sec,title,body)=>{pg++;return`<section class="page"><div class="hd"><span>${sec}</span></div><h2>${title}</h2>${body}<div class="ft"><span>Financial market participation 2020, 2023–2026 · <span data-name>${NAME}</span> · <span data-date>${DATE}</span></span><span>${pg+1}</span></div></section>`};
const SRCTXT=`Source: FIBAM portfolio package v11, NGX source workbook, family credit and repayment log. Data as of ${ASOF}.`;
const usP=(reg('US')/cap),glP=(reg('Global')/cap),ngP=(reg('Nigeria')/cap);
const P=[];
P.push(`<section class="page cover"><div><div class="rule"></div><h1>Financial market participation 2020, 2023–2026</h1><p>A record of the journey and participation in the financial markets: what was traded, how, and where things stand today.</p></div><div><div class="who" data-name>${NAME}</div><p>${DATE}</p></div></section>`);
P.push(page('Summary',`Five calendar years, six markets and three routes in: the journey so far`,
`<div class="kpis"><div><b>5</b><span>calendar years of participation</span></div><div><b>${usd(cap)}</b><span>total capital deployed in markets</span></div><div><b>${f(nTr)}</b><span>trades logged</span></div><div><b>6</b><span>market types: FX, futures, stocks, commodities, metals, crypto</span></div></div>
<p><b>How it began.</b> The journey started in March 2020, when a first personal account was opened as COVID volatility peaked. After a pause, participation resumed in September 2023 and has been continuous since, so it now spans five calendar years: 2020, and 2023 to 2026.</p>
<p><b>How it broadened.</b> From 2023 the journey widened beyond currencies (foreign exchange, or FX) to oil and gold, then in 2024 to silver, US index futures, Bitcoin and Nigerian stocks, and in 2025 to US stocks. Three routes in have been used: personal accounts; accounts with proprietary trading firms (“prop firms”), each beginning as a paid evaluation of trading ability; and 1kHooD, a US stock fund run with a limited partner. Together that is ${D.ACCOUNTS.length} accounts and ${f(nTr)} trades.</p>
<p><b>Prop firms.</b> ${prop.length} prop-firm accounts were run, paying ${usd(fees)} in fees. They provided ${usd(capSz)} of account capacity and produced an account-level result of ${pcs(evPnl/capSz)}. Two stages were passed; no payouts have been received.</p>
<p><b>The equity funds.</b> Both are active. 1kHooD earned ${sg(kh.pnl)} on ${usd(1000)} (${pc(kh.pnl/1000)}). The Nigerian stock account, traded on the Nigerian Exchange (NGX), earned ${ngn(ngxN)} net of fees on ₦150,000 (${pc(ngxN/150000)}).</p>
<p><b>Current position.</b> The net result fell further after 2024, reaching its lowest point of ${usd(cMin[1])} in ${mn(cMin[0])} as new prop-firm fees were paid before that year’s fund gains came through, then recovered to ${usd(overall)} by ${ASOF}. 2025 and 2026 each finished the year net positive, led by the two equity funds. The journey drew on personal (${pc(grp('Personal')/cap)}), friend (${pc(grp('Friend')/cap)}) and family (${pc(grp('Family')/cap)}) capital, of which ${pc(usP)} went into US instruments, ${pc(glP)} into global FX and ${pc(ngP)} into Nigerian stocks. ₦400,000 of ₦720,000 has been repaid to one family lender, and 1kHooD has distributed ${usd(wU)} to its partners.</p>
<div class="note">Figures reflect money that actually moved: prop-firm fees paid, and results from closed trades in personal accounts and the two equity funds. Evaluation-account profit and loss, which stayed inside the evaluation and was never received, is reported separately as a memo item.</div>`,SRCTXT));
P.push(page('1 · Timeline',`Participation has run in two streaks: 2020, then continuously since September 2023`,`<div class="lg"><span><i style="background:#2251FF"></i>Spot FX and price-tracking contracts (CFDs)</span><span><i style="background:#051C2C"></i>US futures</span><span><i style="background:#00A9F4"></i>US equities</span><span><i style="background:#12805C"></i>Nigerian equities</span><span><i style="background:#00A9F4;height:1mm"></i>Event with duration</span></div>${gantt()}
<p style="margin-top:4mm"><b>2020.</b> One personal FX account, opened as COVID volatility peaked. <b>September 2023 to date.</b> The second streak began with a personal account and nine prop-firm accounts in FX and index futures through 2024. Nigerian stocks started in 2024 and 1kHooD in 2025, and six further prop-firm accounts ran in 2026. Both funds remain active. Numbered markers refer to the events on the next page.</p>`,SRCTXT));
P.push(page('1 · Timeline',`Each phase of participation overlapped a major macro or geopolitical shock`,T(['#','Period','Event','Relevance to the markets traded'],EV.map((e,i)=>{const d=x=>new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});return[i+1,e[1]?`${d(e[0])} – ${d(e[1])}`:d(e[0]),e[2],e[3]]}).map(r=>r.map((c,i)=>i?c:c)),'ev')+`<p style="font-size:8pt;color:#5B6B7A">Dates for 2026 events are from public reporting as of ${ASOF}; the Hormuz crisis is ongoing.</p>`,SRCTXT+' Event dates: public sources.'));
const mk=rows.map(r=>[r.k,r.rg,r.acc?'Prop-firm &amp; personal':'Equity fund',f(r.n),pc(r.n/nTr),sg(r.acc+r.fund)]);
P.push(page('2 · Markets',`${pc(usP)} of capital went to US markets and ${pc(glP)} to global FX; Nigerian equities are a small third leg`,
`<h3>Where the capital went, by market</h3>${pie()}<p style="margin-top:2mm">By region: US ${pc(usP)}, Global ${pc(glP)}, Nigeria ${pc(ngP)}.</p>
<h3>By market type</h3>${T(['Market type','Region','Route','Trades','Share of trades','Result'],[...mk,{t:['Total','','',f(nTr),'100%',sg(sum(rows.map(r=>r.acc+r.fund)))]}])}
<p>US covers futures, equity indices (CFDs) and the 1kHooD stock portfolio. Global covers FX, commodities, metals and crypto, all traded through contracts for difference (CFDs), which track a price without owning the asset. Crypto is four BTCUSD trades in one 2024 evaluation. Prop-firm and personal-account results are account-level, including evaluation accounts; equity-fund results are realised gains, with Nigerian stocks converted to USD at prevailing monthly rates.</p>`,SRCTXT));
const pf=['MyFundedFutures','MyFundedFX','FundedNext','The5ers'].map(n=>{const s=prop.filter(a=>a.platform===n);return{n,c:s.length,fee:sum(s.map(a=>a.costOfFund)),sz:sum(s.map(a=>a.size)),each:(()=>{const z=s.map(a=>a.size),lo=Math.min(...z),hi=Math.max(...z);return lo===hi?usd(lo):usd(lo)+'–'+usd(hi)})(),ev:sum(s.map(a=>a.pnl)),ok:s.filter(a=>a.pnl>0).length}});
P.push(page('3 · Entry paths',`Prop evaluations: ${prop.length} attempts, ${usd(fees)} in fees, ${usd(capSz)} of account capacity`,
`<p>${prop.length} prop-firm accounts across four firms provided ${usd(capSz)} of account capacity, for ${usd(fees)} in fees (${f(fees/capSz*100,2)}% of capacity). The aggregate account-level result was ${pcs(evPnl/capSz)}. Two stages were passed at The5ers; no payouts have been received.</p>`+T(['Entry path','Accounts','Capital deployed','Result','Status'],[['Retail investing (personal accounts)',`3: Alpari 2020, Alpari 2023, Nigerian stocks`,usd(829.61),sg(persPnl+ngxU),'Alpari closed; Nigerian stocks active'],['Prop firms',`${prop.length}: four firms`,usd(fees),sg(-fees),'All closed; 0 payouts'],['Managed portfolio (1kHooD)','1: run with a limited partner',usd(1000),sg(kh.pnl),'Active'],{t:['Total',String(D.ACCOUNTS.length),usd(cap),sg(overall),'']}])+
`<h3>Prop firms: totals by firm</h3>${T(['Firm','Accounts','Size per account','Total account size','Total fees paid','Total account-level result','% of total size','Stages passed'],[...pf.map(p=>[p.n,p.c,p.each,usd(p.sz),usd(p.fee,2),sg(p.ev),pcs(p.ev/p.sz),p.ok]),{t:['All four firms',prop.length,'',usd(capSz),usd(fees,2),sg(evPnl),pcs(evPnl/capSz),passed]}])}
<p style="font-size:8pt;color:#5B6B7A">Totals are summed across each firm’s accounts, and each account is counted at its full size, including later stages of the same evaluation.</p><h3>Evaluation fees by firm</h3>${dbar(pf.map(p=>({l:p.n,v:p.fee,c:'#051C2C'})),{lw:130})}
<p style="margin-top:3mm">Three of the five MyFundedFutures evaluations ended at about −4% ($2,000 each), consistent with a fixed maximum-loss rule set by the firm. Retail accounts are self-directed personal accounts. The managed path is 1kHooD, a fund run as general partner with TA as the limited partner. Both stages passed were at The5ers in May 2026.</p>`,SRCTXT));
P.push(page('4 · Funding',`Personal capital reached every route except the two funds; friends and family added the rest`,
`<p>Personal capital (IF) is part of five of the seven destinations below — every route except the two equity funds — and made up ${pc(grp('Personal')/cap)} of the ${usd(cap)} deployed. Friends contributed ${pc(grp('Friend')/cap)}, most of it into 1kHooD; family contributed ${pc(grp('Family')/cap)}, mostly into the MyFundedFutures evaluations and the Nigerian stock account.</p>
<h3>Capital deployed by source</h3>${stack(SRC.map(s=>({l:s,v:fs_[s],c:SC[s]})))}
<div class="lg" style="margin-top:2mm"><span>IF: personal</span><span>TA, PO: friends (TA a close friend; PO contributed in 2020 only)</span><span>MO, BA: family</span></div>
<h3>Where each source went (USD)</h3>${T(['Destination','Personal (IF)','Friend (PO)','Friend (TA)','Family (MO)','Family (BA)','Total'],[...F.map(r=>[r[0],...SRC.map(s=>r[3][s]?f(r[3][s],2):''),f(sum(Object.values(r[3])),2)]),{t:['Total',...SRC.map(s=>f(fs_[s],2)),f(cap,2)]}])}
<p>Any funding not explicitly attributed to a source is treated as personal (IF).</p>
<h3>Received versus deployed (family, ₦)</h3>${T(['Source','Received','Deployed in markets','Into operations'],[['MO (₦420,000 investment, ₦300,000 loan)','₦720,000','≈ ₦398,000','≈ ₦322,000'],['BA','₦1,000,000','₦592,500','₦407,500']])}`,SRCTXT+' Family amounts in naira as recorded.'));
P.push(page('5 · Return of capital',`Return of capital has begun, and 1kHooD distributes to its partners`,
`<p>Partial return of capital has begun: ₦400,000 of ₦720,000 has been repaid to one family lender, and 1kHooD has distributed ${usd(wU)} to its partners.</p><h3>Repayments to family lender MO (₦)</h3>${dbar([{l:'Received',v:720000,c:'#8A97A5'},{l:'Repaid to date',v:400000,c:'#12805C'},{l:'Outstanding',v:320000,c:'#B3261E'}],{fmt:ngn,lw:110})}
${T(['Date','Repaid','Outstanding'],[['17 May 2024','₦100,000','₦620,000'],['7 Jul 2024','₦200,000','₦420,000'],['9 Oct 2024','₦100,000','₦320,000']])}
<p style="font-size:8pt;color:#5B6B7A">Outstanding shown in payment order; the source log lists the 9 Oct 2024 payment first.</p>
<h3>1kHooD: capital, profit and distributions (USD)</h3>${dbar([{l:'Capital contributed (TA, limited partner)',v:1000,c:'#8A97A5'},{l:'Cumulative trading profit',v:kh.pnl},{l:'Distributed to general partner',v:gpU,c:'#051C2C'},{l:'Distributed to TA (limited partner)',v:lpU,c:'#2251FF'},{l:'Implied balance remaining',v:implied,c:'#8A97A5'}],{lw:215})}
<div class="note">${wd.length} withdrawals total ${usd(wU,2)} since Sep 2025, split by the fund’s general and limited partner shares in pounds sterling (${f(gpG/(gpG+lpG)*100)}% and ${f(lpG/(gpG+lpG)*100)}%). They exceed cumulative trading profit of ${usd(kh.pnl,2)}, so they include a partial return of contributed capital; the implied balance is ${usd(implied,2)}.</div>
${T(['Source','Nature of return','Status'],[['IF (personal)','None expected','–'],['PO, TA (friends)','TA: distributions as limited partner in 1kHooD. PO: none','TA receiving; PO none'],['MO (family)','Repayment of credit','₦400,000 of ₦720,000'],['BA (family)','Repayment target','None yet']])}
<p>Returning capital to every source remains a stated target for the journey.</p>`,SRCTXT));
const z=v=>Math.abs(v)<0.5?'':sg(v),yt=yrs.map(y=>[y,z(Y[y].p),z(-Y[y].fee),z(Y[y].kh),z(Y[y].ng),sg(net(y)),sp(net(y)/inPlay(y))]);
P.push(page('6 · Performance',`Year-end results turned positive in 2025 and 2026, after a low at the end of 2024`,
`<h3>By year (USD)</h3>${T(['Year','Personal accounts','Prop fees','1kHooD','Nigerian stocks','Net result','Net result %'],[...yt,{t:['Total',sg(persPnl),sg(-fees),sg(kh.pnl),sg(ngxU),sg(overall),sp(overall/cap)]}])}<p style="font-size:8pt;color:#5B6B7A">Net result % compares each year’s result with the capital in active accounts that year, not with the full ${usd(cap)} deployed over the whole period. The chart below tracks the same idea continuously, from the first account to today.</p>
<div class="lg"><span><i style="background:#051C2C"></i>Personal accounts</span><span><i style="background:#2251FF"></i>Prop-firm evaluations</span><span><i style="background:#12805C"></i>Equity funds</span></div>
<h3>Cumulative result as a share of capital committed</h3>${journeyChart()}
<p style="font-size:8pt;color:#5B6B7A">Each month’s figure is the running result divided by the running capital committed since the first account. For prop-firm accounts, capital committed is the fee paid; for personal accounts and the two funds, it is the capital placed in the account.</p>`,SRCTXT));
P.push(page('6 · Performance',`Prop-firm evaluations dominate the result; the two equity funds are the exception`,
`<h3>By route, result against its own base</h3>${T(['Route','Base','Base amount','Result','Result %'],[['Personal FX accounts (2)','Capital deployed',usd(sum(pers.map(a=>a.size))),sg(persPnl),sp(persPnl/sum(pers.map(a=>a.size)))],['Nigerian stocks','Capital deployed',ngn(150000),`<span class="pos">+${ngn(ngxN)}</span>`,sp(ngxN/150000)],['1kHooD fund','Capital contributed',usd(1000),sg(kh.pnl),sp(kh.pnl/1000)],['Prop-firm fees','Account size',usd(capSz),sg(-fees),`<span class="neg">−${f(fees/capSz*100,2)}%</span>`],['Prop-firm accounts, account level','Account size',usd(capSz),sg(evPnl),sp(evPnl/capSz)]])}
<p style="font-size:8pt;color:#5B6B7A">Nigerian stocks are shown in naira; every other row is in USD.</p>
<h3>By market type, account-level result including evaluation accounts</h3>${dbar(rows.map(r=>({l:`${r.k} · ${pc(r.n/nTr)} of trades`,v:r.acc+r.fund})),{lw:185,rh:19})}
<p style="margin-top:3mm"><b>Status:</b> ${D.ACCOUNTS.filter(a=>a.status==='completed').length} accounts closed, 2 active. Nigerian stocks in naira: ${ngn(ngxG)} gross, ${ngn(ngxF)} fees, ${ngn(ngxN)} net across ${ngx.length} closed trades.</p>`,SRCTXT));
P.push(page('7 · Equity funds',`Both equity funds are active: 1kHooD is up ${pc(kh.pnl/1000)} and Nigerian stocks ${pc(ngxN/150000)} on capital contributed`,
`<p>Results are realised gains only, meaning positions that have been sold. Nigerian stock results are after fees.</p>
${T(['Fund','Started','Capital','Realised result','Return','Closed trades'],[['1kHooD (US stocks)','Feb 2025',usd(1000),sg(kh.pnl),sp(kh.pnl/1000),f(D.KHOOD_TRADES.length)],['Nigerian stocks (NGX)','May 2024','₦150,000',`<span class="pos">+${ngn(ngxN)}</span>`,sp(ngxN/150000),f(ngx.length)]])}
<h3>Cumulative return on capital contributed (%)</h3><div class="lg"><span><i style="background:#00A9F4"></i>1kHooD (US stocks)</span><span><i style="background:#12805C"></i>Nigerian stocks</span></div>
${area({ss:[{pts:ngS,c:'#12805C'},{pts:khS,c:'#00A9F4'}],x0:mi('2024-05-01'),x1:80,y0:0,y1:80,st:20,fmt:v=>v+'%',H:210,marks:[{m:80,v:khS.at(-1)[1],t:`1kHooD ${pcs(khS.at(-1)[1]/100)}`,a:'end',dx:-8,dy:-9,c:'#00A9F4'},{m:80,v:ngS.at(-1)[1],t:`Nigerian stocks ${pcs(ngS.at(-1)[1]/100)}`,a:'end',dx:-8,dy:17,c:'#12805C'}]})}
<h3>1kHooD: cumulative trading result and distributions (USD)</h3><div class="lg"><span><i style="background:#00A9F4"></i>Trading result</span><span><i style="background:#051C2C"></i>Distributed to partners</span></div>
${area({ss:[{pts:khU,c:'#00A9F4'},{pts:khD,c:'#051C2C'}],x0:mi('2025-02-01'),x1:80,y0:0,y1:1600,st:400,H:210,marks:[{m:80,v:khD.at(-1)[1],t:`Distributed ${usd(khD.at(-1)[1])}`,a:'end',dx:-8,dy:-9},{m:80,v:khU.at(-1)[1],t:`Trading result ${sg(khU.at(-1)[1])}`.replace(/<[^>]+>/g,''),a:'end',dx:-8,dy:17,c:'#00A9F4'}]})}
<p style="margin-top:2mm">Distributions so far total ${usd(wU)} against a cumulative trading result of ${usd(kh.pnl)}. The return of capital page shows how they were split between the general partner and the limited partner.</p>`,SRCTXT));
P.push(page('8 · Research approach',`The approach is pattern recognition, and trading has become more selective: ${avg('2024')} trades per account in 2024, ${avg('2026')} in 2026`,
`<p><b>Primary approach.</b> Generating value from the markets through the application of the art, science and technology of pattern recognition.</p>
<div class="cols"><div><h3>Art</h3><p>Reading structure, context and behaviour in price: the discretionary judgement of what a pattern means now.</p></div><div><h3>Science</h3><p>Testing whether a pattern repeats with an edge: samples, expectancy and risk limits rather than anecdote.</p></div><div><h3>Technology</h3><p>Encoding what works into indicators, dashboards and automated systems so it can be applied without drift.</p></div></div>
<h3>Supporting lenses</h3>${T(['Lens','Role'],[['Technical analysis','Structure, levels, momentum and reversal signals across FX, futures and stocks'],['Fundamentals','Sector and company selection for the equity funds, including thematic sector intelligence'],['Events','Macro and geopolitical catalysts: rates, elections, wars, supply shocks (see events, page 4)']])}
<h3>How trading has changed since 2024</h3>${T(['Prop-firm accounts opened in','2024','2026'],[['Number of accounts',c24.n,c26.n],['Average trades per account',avg('2024'),avg('2026')],['Most trades in one account',Math.max(...prop.filter(a=>a.startDate<'2025').map(a=>a.trades)),Math.max(...prop.filter(a=>a.startDate>'2025').map(a=>a.trades))],['Result against account size',sp(c24.pl/c24.sz),sp(c26.pl/c26.sz)],['Accounts finishing positive',`${c24.up} of ${c24.n}`,`${c26.up} of ${c26.n}`]])}<p>In plain terms: fewer trades per account, smaller losses against account size, and the first accounts to finish ahead. With only 15 accounts, and different firms and account sizes in each year, this shows a direction rather than proving a cause. Averages use the accounts that have trade records.</p>
<h3>Tooling built along the way</h3><p>Rule-based systems and dashboards are part of the approach: automated trading rules for two trading platforms, an intraday trading engine, charting indicators, and a sector-intelligence tool.</p>`,SRCTXT));
P.push(page('Notes',`Basis of preparation`,
`<p><b>Basis of the figures.</b> Personal accounts show the account’s realised result; prop firms show the evaluation fee paid, not the evaluation account’s own profit or loss; funds show trading result before the general and limited partner split. Evaluation-account profit and loss is reported separately, as a memo item.</p>
<p><b>Currency.</b> Reported in USD. Nigerian stock results are recorded in naira and converted to USD at approximate monthly ₦/$ levels: recorded rates for 2024 and published Central Bank of Nigeria levels for 2025–26 (about ₦1,360–1,530). Family amounts are shown in naira as recorded.</p>
<p><b>Nigerian stocks.</b> Gains are shown net of fees: ${ngn(ngxG)} gross, less ${ngn(ngxF)} in fees, for ${ngn(ngxN)} net. One open position (6 shares of Geregu Power, bought for ₦5,400) has not been sold and is excluded from the results; it was running ₦446 below cost.</p>
<p><b>Data gaps.</b> A few accounts rely on account-level summaries rather than complete trade-by-trade records — Alpari 2020, two of the MyFundedFX evaluations, and Alpari 2023. These differences are minor and do not change the overall picture.</p>
<p><b>Funding rule.</b> Unattributed funding is personal. No prop payouts, no other accounts, and no participation in 2021–22.</p>
<p><b>Sources.</b> Account and trade-level portfolio records, Nigerian stock trade records, and the family credit and repayment log. Event dates are from public reporting. Data as of ${ASOF}.</p>
<p><b>Terms.</b> A prop firm is a proprietary trading firm that lets a trader use its account after passing a paid evaluation. FX is trading one currency against another; futures are standardised contracts on an index or commodity. A CFD is a contract for difference, which tracks a price without owning the asset. NGX is the Nigerian Exchange, where Nigerian stocks are traded. Alpari is the online broker used for the two personal accounts. In 1kHooD, the general partner runs the fund and the limited partner provides the capital.</p>`,SRCTXT));
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Financial market participation 2020, 2023–2026 · ${NAME}</title><link rel="stylesheet" href="assets/report.css"><script>
/* To change the name or date shown throughout the report, edit the two values below. */
var REPORT={name:"${NAME}",date:"${DATE}"};
</script></head><body><div class="bar"><span>Financial market participation 2020, 2023–2026</span><a href="${PDF}" download data-pdf-name="${NAME}">Download PDF</a></div>${P.join('\n')}<script>(function(){var q=function(s){return document.querySelectorAll(s)};
q('[data-name]').forEach(function(e){e.textContent=REPORT.name});q('[data-date]').forEach(function(e){e.textContent=REPORT.date});
document.title='Financial market participation 2020, 2023–2026 · '+REPORT.name;
var a=q('.bar a')[0];if(REPORT.name!==a.getAttribute('data-pdf-name')){a.addEventListener('click',function(ev){ev.preventDefault();window.print()})}
document.documentElement.style.setProperty('--z',Math.min(1,innerWidth/800))})()</script></body></html>`;
fs.writeFileSync(R+'/index.html',html);
console.log(JSON.stringify({cap,fs_,overall:+overall.toFixed(2),ngxU:+ngxU.toFixed(2),ngxN,fees,persPnl,evPnl,passed,nTr,net:yrs.map(y=>+net(y).toFixed(1)),wU,lpU:+lpU.toFixed(1),implied:+implied.toFixed(2),avg24:avg('2024'),avg26:avg('2026'),rows:rows.map(r=>[r.k,r.n,+r.acc.toFixed(0),+r.fund.toFixed(0)])}));
